--------------------------------------------------------
--  DDL for Table APP_USER_PRODUK_CATEGORY
--------------------------------------------------------

  CREATE TABLE "APP_USER_PRODUK_CATEGORY" 
   (	"USER_NAME" VARCHAR2(30), 
	"PROD_CATEGORY" VARCHAR2(40), 
	"CATEGORY_DESC" VARCHAR2(255)
   ) ;
REM INSERTING into APP_USER_PRODUK_CATEGORY
SET DEFINE OFF;
Insert into APP_USER_PRODUK_CATEGORY (USER_NAME,PROD_CATEGORY,CATEGORY_DESC) values ('admin','CT001','Food');
Insert into APP_USER_PRODUK_CATEGORY (USER_NAME,PROD_CATEGORY,CATEGORY_DESC) values ('L0010','CT001','Food');
Insert into APP_USER_PRODUK_CATEGORY (USER_NAME,PROD_CATEGORY,CATEGORY_DESC) values ('N0017','CT001','Food');
Insert into APP_USER_PRODUK_CATEGORY (USER_NAME,PROD_CATEGORY,CATEGORY_DESC) values ('R0035','CT001','Food');
Insert into APP_USER_PRODUK_CATEGORY (USER_NAME,PROD_CATEGORY,CATEGORY_DESC) values ('S0037','CT001','Food');
Insert into APP_USER_PRODUK_CATEGORY (USER_NAME,PROD_CATEGORY,CATEGORY_DESC) values ('S0040','CT001','Food');
Insert into APP_USER_PRODUK_CATEGORY (USER_NAME,PROD_CATEGORY,CATEGORY_DESC) values ('G0008','CT001','Food');
Insert into APP_USER_PRODUK_CATEGORY (USER_NAME,PROD_CATEGORY,CATEGORY_DESC) values ('G0008','CT002','Non Food');
Insert into APP_USER_PRODUK_CATEGORY (USER_NAME,PROD_CATEGORY,CATEGORY_DESC) values ('R0042','CT002','Non Food');
Insert into APP_USER_PRODUK_CATEGORY (USER_NAME,PROD_CATEGORY,CATEGORY_DESC) values ('C0006','CT001','Food');
Insert into APP_USER_PRODUK_CATEGORY (USER_NAME,PROD_CATEGORY,CATEGORY_DESC) values ('E0016','CT002','Non Food');
Insert into APP_USER_PRODUK_CATEGORY (USER_NAME,PROD_CATEGORY,CATEGORY_DESC) values ('A0054','CT001','Food');
Insert into APP_USER_PRODUK_CATEGORY (USER_NAME,PROD_CATEGORY,CATEGORY_DESC) values ('A0054','CT002','Non Food');
Insert into APP_USER_PRODUK_CATEGORY (USER_NAME,PROD_CATEGORY,CATEGORY_DESC) values ('A0055','CT001','Food');
Insert into APP_USER_PRODUK_CATEGORY (USER_NAME,PROD_CATEGORY,CATEGORY_DESC) values ('A0055','CT002','Non Food');
Insert into APP_USER_PRODUK_CATEGORY (USER_NAME,PROD_CATEGORY,CATEGORY_DESC) values ('B0001','CT001','Food');
Insert into APP_USER_PRODUK_CATEGORY (USER_NAME,PROD_CATEGORY,CATEGORY_DESC) values ('S0032','CT002','Non Food');
Insert into APP_USER_PRODUK_CATEGORY (USER_NAME,PROD_CATEGORY,CATEGORY_DESC) values ('B0011','CT002','Non Food');
Insert into APP_USER_PRODUK_CATEGORY (USER_NAME,PROD_CATEGORY,CATEGORY_DESC) values ('D0013','CT001','Food');
Insert into APP_USER_PRODUK_CATEGORY (USER_NAME,PROD_CATEGORY,CATEGORY_DESC) values ('D0013','CT002','Non Food');
Insert into APP_USER_PRODUK_CATEGORY (USER_NAME,PROD_CATEGORY,CATEGORY_DESC) values ('D0018','CT001','Food');
Insert into APP_USER_PRODUK_CATEGORY (USER_NAME,PROD_CATEGORY,CATEGORY_DESC) values ('D0019','CT002','Non Food');
Insert into APP_USER_PRODUK_CATEGORY (USER_NAME,PROD_CATEGORY,CATEGORY_DESC) values ('F0018','CT001','Food');
Insert into APP_USER_PRODUK_CATEGORY (USER_NAME,PROD_CATEGORY,CATEGORY_DESC) values ('D0024','CT001','Food');
Insert into APP_USER_PRODUK_CATEGORY (USER_NAME,PROD_CATEGORY,CATEGORY_DESC) values ('D0022','CT002','Non Food');
Insert into APP_USER_PRODUK_CATEGORY (USER_NAME,PROD_CATEGORY,CATEGORY_DESC) values ('D0025','CT001','Food');
Insert into APP_USER_PRODUK_CATEGORY (USER_NAME,PROD_CATEGORY,CATEGORY_DESC) values ('D0025','CT002','Non Food');
Insert into APP_USER_PRODUK_CATEGORY (USER_NAME,PROD_CATEGORY,CATEGORY_DESC) values ('F0011','CT001','Food');
Insert into APP_USER_PRODUK_CATEGORY (USER_NAME,PROD_CATEGORY,CATEGORY_DESC) values ('F0011','CT002','Non Food');
Insert into APP_USER_PRODUK_CATEGORY (USER_NAME,PROD_CATEGORY,CATEGORY_DESC) values ('NB005','CT001','Food');
Insert into APP_USER_PRODUK_CATEGORY (USER_NAME,PROD_CATEGORY,CATEGORY_DESC) values ('H0010','CT001','Food');
Insert into APP_USER_PRODUK_CATEGORY (USER_NAME,PROD_CATEGORY,CATEGORY_DESC) values ('H0013','CT002','Non Food');
Insert into APP_USER_PRODUK_CATEGORY (USER_NAME,PROD_CATEGORY,CATEGORY_DESC) values ('I0009','CT001','Food');
Insert into APP_USER_PRODUK_CATEGORY (USER_NAME,PROD_CATEGORY,CATEGORY_DESC) values ('I0018','CT001','Food');
Insert into APP_USER_PRODUK_CATEGORY (USER_NAME,PROD_CATEGORY,CATEGORY_DESC) values ('I0018','CT002','Non Food');
Insert into APP_USER_PRODUK_CATEGORY (USER_NAME,PROD_CATEGORY,CATEGORY_DESC) values ('M0003','CT002','Non Food');
Insert into APP_USER_PRODUK_CATEGORY (USER_NAME,PROD_CATEGORY,CATEGORY_DESC) values ('M0009','CT002','Non Food');
Insert into APP_USER_PRODUK_CATEGORY (USER_NAME,PROD_CATEGORY,CATEGORY_DESC) values ('M0011','CT002','Non Food');
Insert into APP_USER_PRODUK_CATEGORY (USER_NAME,PROD_CATEGORY,CATEGORY_DESC) values ('M0012','CT002','Non Food');
Insert into APP_USER_PRODUK_CATEGORY (USER_NAME,PROD_CATEGORY,CATEGORY_DESC) values ('M0015','CT001','Food');
Insert into APP_USER_PRODUK_CATEGORY (USER_NAME,PROD_CATEGORY,CATEGORY_DESC) values ('M0015','CT002','Non Food');
Insert into APP_USER_PRODUK_CATEGORY (USER_NAME,PROD_CATEGORY,CATEGORY_DESC) values ('M0018','CT002','Non Food');
Insert into APP_USER_PRODUK_CATEGORY (USER_NAME,PROD_CATEGORY,CATEGORY_DESC) values ('M0032','CT001','Food');
Insert into APP_USER_PRODUK_CATEGORY (USER_NAME,PROD_CATEGORY,CATEGORY_DESC) values ('M0032','CT002','Non Food');
Insert into APP_USER_PRODUK_CATEGORY (USER_NAME,PROD_CATEGORY,CATEGORY_DESC) values ('N0005','CT001','Food');
Insert into APP_USER_PRODUK_CATEGORY (USER_NAME,PROD_CATEGORY,CATEGORY_DESC) values ('N0005','CT002','Non Food');
Insert into APP_USER_PRODUK_CATEGORY (USER_NAME,PROD_CATEGORY,CATEGORY_DESC) values ('P0001','CT002','Non Food');
Insert into APP_USER_PRODUK_CATEGORY (USER_NAME,PROD_CATEGORY,CATEGORY_DESC) values ('P0002','CT001','Food');
Insert into APP_USER_PRODUK_CATEGORY (USER_NAME,PROD_CATEGORY,CATEGORY_DESC) values ('P0006','CT001','Food');
Insert into APP_USER_PRODUK_CATEGORY (USER_NAME,PROD_CATEGORY,CATEGORY_DESC) values ('A0030','CT002','Non Food');
Insert into APP_USER_PRODUK_CATEGORY (USER_NAME,PROD_CATEGORY,CATEGORY_DESC) values ('A0033','CT002','Non Food');
Insert into APP_USER_PRODUK_CATEGORY (USER_NAME,PROD_CATEGORY,CATEGORY_DESC) values ('A0073','CT002','Non Food');
Insert into APP_USER_PRODUK_CATEGORY (USER_NAME,PROD_CATEGORY,CATEGORY_DESC) values ('Y0002','CT002','Non Food');
Insert into APP_USER_PRODUK_CATEGORY (USER_NAME,PROD_CATEGORY,CATEGORY_DESC) values ('T0003','CT002','Non Food');
Insert into APP_USER_PRODUK_CATEGORY (USER_NAME,PROD_CATEGORY,CATEGORY_DESC) values ('K0007','CT001','Food');
Insert into APP_USER_PRODUK_CATEGORY (USER_NAME,PROD_CATEGORY,CATEGORY_DESC) values ('P0009','CT002','Non Food');
Insert into APP_USER_PRODUK_CATEGORY (USER_NAME,PROD_CATEGORY,CATEGORY_DESC) values ('R0003','CT002','Non Food');
Insert into APP_USER_PRODUK_CATEGORY (USER_NAME,PROD_CATEGORY,CATEGORY_DESC) values ('A0071','CT001','Food');
Insert into APP_USER_PRODUK_CATEGORY (USER_NAME,PROD_CATEGORY,CATEGORY_DESC) values ('R0007','CT001','Food');
Insert into APP_USER_PRODUK_CATEGORY (USER_NAME,PROD_CATEGORY,CATEGORY_DESC) values ('S0044','CT001','Food');
Insert into APP_USER_PRODUK_CATEGORY (USER_NAME,PROD_CATEGORY,CATEGORY_DESC) values ('Y0011','CT001','Food');
Insert into APP_USER_PRODUK_CATEGORY (USER_NAME,PROD_CATEGORY,CATEGORY_DESC) values ('R0033','CT001','Food');
Insert into APP_USER_PRODUK_CATEGORY (USER_NAME,PROD_CATEGORY,CATEGORY_DESC) values ('R0029','CT001','Food');
Insert into APP_USER_PRODUK_CATEGORY (USER_NAME,PROD_CATEGORY,CATEGORY_DESC) values ('R0029','CT002','Non Food');
Insert into APP_USER_PRODUK_CATEGORY (USER_NAME,PROD_CATEGORY,CATEGORY_DESC) values ('R0030','CT001','Food');
Insert into APP_USER_PRODUK_CATEGORY (USER_NAME,PROD_CATEGORY,CATEGORY_DESC) values ('R0030','CT002','Non Food');
Insert into APP_USER_PRODUK_CATEGORY (USER_NAME,PROD_CATEGORY,CATEGORY_DESC) values ('R0031','CT002','Non Food');
Insert into APP_USER_PRODUK_CATEGORY (USER_NAME,PROD_CATEGORY,CATEGORY_DESC) values ('S0002','CT001','Food');
Insert into APP_USER_PRODUK_CATEGORY (USER_NAME,PROD_CATEGORY,CATEGORY_DESC) values ('S0020','CT001','Food');
Insert into APP_USER_PRODUK_CATEGORY (USER_NAME,PROD_CATEGORY,CATEGORY_DESC) values ('S0020','CT002','Non Food');
Insert into APP_USER_PRODUK_CATEGORY (USER_NAME,PROD_CATEGORY,CATEGORY_DESC) values ('S0033','CT002','Non Food');
Insert into APP_USER_PRODUK_CATEGORY (USER_NAME,PROD_CATEGORY,CATEGORY_DESC) values ('S0034','CT001','Food');
Insert into APP_USER_PRODUK_CATEGORY (USER_NAME,PROD_CATEGORY,CATEGORY_DESC) values ('S0034','CT002','Non Food');
Insert into APP_USER_PRODUK_CATEGORY (USER_NAME,PROD_CATEGORY,CATEGORY_DESC) values ('W0001','CT001','Food');
Insert into APP_USER_PRODUK_CATEGORY (USER_NAME,PROD_CATEGORY,CATEGORY_DESC) values ('W0003','CT002','Non Food');
Insert into APP_USER_PRODUK_CATEGORY (USER_NAME,PROD_CATEGORY,CATEGORY_DESC) values ('Y0006','CT001','Food');
Insert into APP_USER_PRODUK_CATEGORY (USER_NAME,PROD_CATEGORY,CATEGORY_DESC) values ('Y0014','CT002','Non Food');
Insert into APP_USER_PRODUK_CATEGORY (USER_NAME,PROD_CATEGORY,CATEGORY_DESC) values ('Z0006','CT001','Food');
Insert into APP_USER_PRODUK_CATEGORY (USER_NAME,PROD_CATEGORY,CATEGORY_DESC) values ('L0003','CT001','Food');
Insert into APP_USER_PRODUK_CATEGORY (USER_NAME,PROD_CATEGORY,CATEGORY_DESC) values ('S0023','CT002','Non Food');
Insert into APP_USER_PRODUK_CATEGORY (USER_NAME,PROD_CATEGORY,CATEGORY_DESC) values ('M0005','CT001','Food');
Insert into APP_USER_PRODUK_CATEGORY (USER_NAME,PROD_CATEGORY,CATEGORY_DESC) values ('O0001','CT002','Non Food');
Insert into APP_USER_PRODUK_CATEGORY (USER_NAME,PROD_CATEGORY,CATEGORY_DESC) values ('A0012','CT002','Non Food');
Insert into APP_USER_PRODUK_CATEGORY (USER_NAME,PROD_CATEGORY,CATEGORY_DESC) values ('M0013','CT002','Non Food');
Insert into APP_USER_PRODUK_CATEGORY (USER_NAME,PROD_CATEGORY,CATEGORY_DESC) values ('Y0003','CT002','Non Food');
Insert into APP_USER_PRODUK_CATEGORY (USER_NAME,PROD_CATEGORY,CATEGORY_DESC) values ('A0022','CT001','Food');
Insert into APP_USER_PRODUK_CATEGORY (USER_NAME,PROD_CATEGORY,CATEGORY_DESC) values ('Y0017','CT002','Non Food');
Insert into APP_USER_PRODUK_CATEGORY (USER_NAME,PROD_CATEGORY,CATEGORY_DESC) values ('A0060','CT002','Non Food');
Insert into APP_USER_PRODUK_CATEGORY (USER_NAME,PROD_CATEGORY,CATEGORY_DESC) values ('A0063','CT002','Non Food');
Insert into APP_USER_PRODUK_CATEGORY (USER_NAME,PROD_CATEGORY,CATEGORY_DESC) values ('H0023','CT002','Non Food');
Insert into APP_USER_PRODUK_CATEGORY (USER_NAME,PROD_CATEGORY,CATEGORY_DESC) values ('A0066','CT001','Food');
Insert into APP_USER_PRODUK_CATEGORY (USER_NAME,PROD_CATEGORY,CATEGORY_DESC) values ('B0014','CT002','Non Food');
Insert into APP_USER_PRODUK_CATEGORY (USER_NAME,PROD_CATEGORY,CATEGORY_DESC) values ('R0017','CT001','Food');
Insert into APP_USER_PRODUK_CATEGORY (USER_NAME,PROD_CATEGORY,CATEGORY_DESC) values ('A0067','CT001','Food');
Insert into APP_USER_PRODUK_CATEGORY (USER_NAME,PROD_CATEGORY,CATEGORY_DESC) values ('C0004','CT001','Food');
Insert into APP_USER_PRODUK_CATEGORY (USER_NAME,PROD_CATEGORY,CATEGORY_DESC) values ('F0013','CT001','Food');
Insert into APP_USER_PRODUK_CATEGORY (USER_NAME,PROD_CATEGORY,CATEGORY_DESC) values ('G0007','CT001','Food');
--------------------------------------------------------
--  DDL for Index APP_USER_PRODUK_CATEGORY_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "APP_USER_PRODUK_CATEGORY_PK" ON "APP_USER_PRODUK_CATEGORY" ("USER_NAME", "PROD_CATEGORY") 
  ;
--------------------------------------------------------
--  Constraints for Table APP_USER_PRODUK_CATEGORY
--------------------------------------------------------

  ALTER TABLE "APP_USER_PRODUK_CATEGORY" MODIFY ("USER_NAME" NOT NULL ENABLE);
  ALTER TABLE "APP_USER_PRODUK_CATEGORY" MODIFY ("PROD_CATEGORY" NOT NULL ENABLE);
  ALTER TABLE "APP_USER_PRODUK_CATEGORY" ADD CONSTRAINT "APP_USER_PRODUK_CATEGORY_PK" PRIMARY KEY ("USER_NAME", "PROD_CATEGORY") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table APP_USER_PRODUK_CATEGORY
--------------------------------------------------------

  ALTER TABLE "APP_USER_PRODUK_CATEGORY" ADD CONSTRAINT "APP_USER_PRODUK_APP_USER__FK1" FOREIGN KEY ("USER_NAME")
	  REFERENCES "APP_USER_ACCESS" ("USER_NAME") ON DELETE CASCADE ENABLE;
