--------------------------------------------------------
--  File created - Monday-October-07-2019   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table APP_ROLES
--------------------------------------------------------

  CREATE TABLE "APP_ROLES" 
   (	"ID" NUMBER(10,0), 
	"NAME" VARCHAR2(30), 
	"DESCR" VARCHAR2(20), 
	"LABEL" VARCHAR2(30), 
	"ROLE_TYPE" VARCHAR2(20) DEFAULT 'AREA', 
	"FORWARD_FLG" VARCHAR2(1) DEFAULT 'N', 
	"ADDENDUM_AREA" VARCHAR2(1) DEFAULT 'N', 
	"UNAPPROVED" VARCHAR2(1) DEFAULT 'N', 
	"PRINT_COUNT" VARCHAR2(1) DEFAULT 'N', 
	"BUDGET_STATUS" VARCHAR2(1) DEFAULT 'N', 
	"APPROVAL_BUDGET" VARCHAR2(1) DEFAULT 'N'
   ) ;
REM INSERTING into APP_ROLES
SET DEFINE OFF;
Insert into APP_ROLES (ID,NAME,DESCR,LABEL,ROLE_TYPE,FORWARD_FLG,ADDENDUM_AREA,UNAPPROVED,PRINT_COUNT,BUDGET_STATUS,APPROVAL_BUDGET) values (1,'adminapp','Admin Aplikasi','Admin Aplikasi','HO','N','N','N','N','N','N');
Insert into APP_ROLES (ID,NAME,DESCR,LABEL,ROLE_TYPE,FORWARD_FLG,ADDENDUM_AREA,UNAPPROVED,PRINT_COUNT,BUDGET_STATUS,APPROVAL_BUDGET) values (36,'JBE','JBE','JBE','AREA','N','N','N','N','N','N');
Insert into APP_ROLES (ID,NAME,DESCR,LABEL,ROLE_TYPE,FORWARD_FLG,ADDENDUM_AREA,UNAPPROVED,PRINT_COUNT,BUDGET_STATUS,APPROVAL_BUDGET) values (37,'AS/KAS','AS/KAS','AS/KAS','AREA','N','N','N','N','N','N');
Insert into APP_ROLES (ID,NAME,DESCR,LABEL,ROLE_TYPE,FORWARD_FLG,ADDENDUM_AREA,UNAPPROVED,PRINT_COUNT,BUDGET_STATUS,APPROVAL_BUDGET) values (38,'TMS/BE','TMS/BE','TMS/BE','AREA','N','N','N','N','N','N');
Insert into APP_ROLES (ID,NAME,DESCR,LABEL,ROLE_TYPE,FORWARD_FLG,ADDENDUM_AREA,UNAPPROVED,PRINT_COUNT,BUDGET_STATUS,APPROVAL_BUDGET) values (39,'SAS/SKAS','SAS/SKAS','SAS/SKAS','AREA','N','N','N','N','N','N');
Insert into APP_ROLES (ID,NAME,DESCR,LABEL,ROLE_TYPE,FORWARD_FLG,ADDENDUM_AREA,UNAPPROVED,PRINT_COUNT,BUDGET_STATUS,APPROVAL_BUDGET) values (40,'SBE','SBE','SBE','AREA','N','N','N','N','N','N');
Insert into APP_ROLES (ID,NAME,DESCR,LABEL,ROLE_TYPE,FORWARD_FLG,ADDENDUM_AREA,UNAPPROVED,PRINT_COUNT,BUDGET_STATUS,APPROVAL_BUDGET) values (41,'AM/KAM','AM/KAM','AM/KAM','AREA','N','N','N','N','N','N');
Insert into APP_ROLES (ID,NAME,DESCR,LABEL,ROLE_TYPE,FORWARD_FLG,ADDENDUM_AREA,UNAPPROVED,PRINT_COUNT,BUDGET_STATUS,APPROVAL_BUDGET) values (42,'BM/TMM','BM/TMM','BM/TMM','AREA','N','N','N','N','N','N');
Insert into APP_ROLES (ID,NAME,DESCR,LABEL,ROLE_TYPE,FORWARD_FLG,ADDENDUM_AREA,UNAPPROVED,PRINT_COUNT,BUDGET_STATUS,APPROVAL_BUDGET) values (43,'RM/SKAM','RM/SKAM','RM/SKAM','AREA','N','N','N','N','N','N');
Insert into APP_ROLES (ID,NAME,DESCR,LABEL,ROLE_TYPE,FORWARD_FLG,ADDENDUM_AREA,UNAPPROVED,PRINT_COUNT,BUDGET_STATUS,APPROVAL_BUDGET) values (44,'SBM/STMM','SBM/STMM','SBM/STMM','AREA','N','N','N','N','N','N');
Insert into APP_ROLES (ID,NAME,DESCR,LABEL,ROLE_TYPE,FORWARD_FLG,ADDENDUM_AREA,UNAPPROVED,PRINT_COUNT,BUDGET_STATUS,APPROVAL_BUDGET) values (45,'GSM/NKAM','GSM/NKAM','GSM/NKAM','AREA','N','N','N','N','N','N');
Insert into APP_ROLES (ID,NAME,DESCR,LABEL,ROLE_TYPE,FORWARD_FLG,ADDENDUM_AREA,UNAPPROVED,PRINT_COUNT,BUDGET_STATUS,APPROVAL_BUDGET) values (46,'VP','VP','VP','AREA','N','N','N','N','N','N');
Insert into APP_ROLES (ID,NAME,DESCR,LABEL,ROLE_TYPE,FORWARD_FLG,ADDENDUM_AREA,UNAPPROVED,PRINT_COUNT,BUDGET_STATUS,APPROVAL_BUDGET) values (47,'MM','MM','MM','AREA','N','N','N','N','N','N');
Insert into APP_ROLES (ID,NAME,DESCR,LABEL,ROLE_TYPE,FORWARD_FLG,ADDENDUM_AREA,UNAPPROVED,PRINT_COUNT,BUDGET_STATUS,APPROVAL_BUDGET) values (48,'SVP','SVP','SVP','HO','N','N','Y','Y','N','N');
Insert into APP_ROLES (ID,NAME,DESCR,LABEL,ROLE_TYPE,FORWARD_FLG,ADDENDUM_AREA,UNAPPROVED,PRINT_COUNT,BUDGET_STATUS,APPROVAL_BUDGET) values (49,'MKTS-Supervisor','MKTS-Supervisor','MKTS-Supervisor','HO','N','Y','N','Y','Y','N');
Insert into APP_ROLES (ID,NAME,DESCR,LABEL,ROLE_TYPE,FORWARD_FLG,ADDENDUM_AREA,UNAPPROVED,PRINT_COUNT,BUDGET_STATUS,APPROVAL_BUDGET) values (50,'MKTS-Admin','MKTS-Admin','MKTS-Admin','HO','N','Y','N','Y','N','N');
Insert into APP_ROLES (ID,NAME,DESCR,LABEL,ROLE_TYPE,FORWARD_FLG,ADDENDUM_AREA,UNAPPROVED,PRINT_COUNT,BUDGET_STATUS,APPROVAL_BUDGET) values (51,'MIS','MIS','MIS','HO','N','Y','Y','N','N','Y');
Insert into APP_ROLES (ID,NAME,DESCR,LABEL,ROLE_TYPE,FORWARD_FLG,ADDENDUM_AREA,UNAPPROVED,PRINT_COUNT,BUDGET_STATUS,APPROVAL_BUDGET) values (52,'DD','DD','DD','AREA','N','N','N','N','N','N');
Insert into APP_ROLES (ID,NAME,DESCR,LABEL,ROLE_TYPE,FORWARD_FLG,ADDENDUM_AREA,UNAPPROVED,PRINT_COUNT,BUDGET_STATUS,APPROVAL_BUDGET) values (53,'MKTS-BudgetControl','MKTS-BudgetControl','MKTS-BudgetControl','HO','N','N','N','N','N','N');
Insert into APP_ROLES (ID,NAME,DESCR,LABEL,ROLE_TYPE,FORWARD_FLG,ADDENDUM_AREA,UNAPPROVED,PRINT_COUNT,BUDGET_STATUS,APPROVAL_BUDGET) values (54,'SVP_B','SVP_B','SVP_B','HO','N','N','N','N','N','Y');
Insert into APP_ROLES (ID,NAME,DESCR,LABEL,ROLE_TYPE,FORWARD_FLG,ADDENDUM_AREA,UNAPPROVED,PRINT_COUNT,BUDGET_STATUS,APPROVAL_BUDGET) values (17,'MD','MD','MD','HO','Y','N','N','N','N','N');
Insert into APP_ROLES (ID,NAME,DESCR,LABEL,ROLE_TYPE,FORWARD_FLG,ADDENDUM_AREA,UNAPPROVED,PRINT_COUNT,BUDGET_STATUS,APPROVAL_BUDGET) values (35,'JAS/JKAS','JAS/JKAS','JAS/JKAS','AREA','N','N','N','N','N','N');
--------------------------------------------------------
--  DDL for Index APP_ROLES_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "APP_ROLES_PK" ON "APP_ROLES" ("ID") 
  ;
--------------------------------------------------------
--  DDL for Index APP_ROLES_UK
--------------------------------------------------------

  CREATE UNIQUE INDEX "APP_ROLES_UK" ON "APP_ROLES" ("NAME") 
  ;
--------------------------------------------------------
--  Constraints for Table APP_ROLES
--------------------------------------------------------

  ALTER TABLE "APP_ROLES" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "APP_ROLES" MODIFY ("NAME" NOT NULL ENABLE);
  ALTER TABLE "APP_ROLES" MODIFY ("LABEL" NOT NULL ENABLE);
  ALTER TABLE "APP_ROLES" MODIFY ("ROLE_TYPE" NOT NULL ENABLE);
  ALTER TABLE "APP_ROLES" MODIFY ("FORWARD_FLG" NOT NULL ENABLE);
  ALTER TABLE "APP_ROLES" ADD CONSTRAINT "APP_ROLES_PK" PRIMARY KEY ("ID") ENABLE;
  ALTER TABLE "APP_ROLES" ADD CONSTRAINT "APP_ROLES_UK" UNIQUE ("NAME") ENABLE;
  ALTER TABLE "APP_ROLES" MODIFY ("ADDENDUM_AREA" NOT NULL ENABLE);
  ALTER TABLE "APP_ROLES" MODIFY ("UNAPPROVED" NOT NULL ENABLE);
  ALTER TABLE "APP_ROLES" MODIFY ("PRINT_COUNT" NOT NULL ENABLE);
  ALTER TABLE "APP_ROLES" MODIFY ("BUDGET_STATUS" NOT NULL ENABLE);
  ALTER TABLE "APP_ROLES" MODIFY ("APPROVAL_BUDGET" NOT NULL ENABLE);
