--------------------------------------------------------
--  File created - Monday-October-07-2019   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table APP_USER_LOC
--------------------------------------------------------

  CREATE TABLE "APP_USER_LOC" 
   (	"USER_NAME" VARCHAR2(30), 
	"LOCATION_CODE" VARCHAR2(20), 
	"LOCATION_DESC" VARCHAR2(250)
   ) ;
REM INSERTING into APP_USER_LOC
SET DEFINE OFF;
Insert into APP_USER_LOC (USER_NAME,LOCATION_CODE,LOCATION_DESC) values ('C0006','SLJ008',null);
Insert into APP_USER_LOC (USER_NAME,LOCATION_CODE,LOCATION_DESC) values ('C0006','SLM004',null);
Insert into APP_USER_LOC (USER_NAME,LOCATION_CODE,LOCATION_DESC) values ('C0006','SLS014',null);
Insert into APP_USER_LOC (USER_NAME,LOCATION_CODE,LOCATION_DESC) values ('E0016','SLJ008',null);
Insert into APP_USER_LOC (USER_NAME,LOCATION_CODE,LOCATION_DESC) values ('E0016','SLM004',null);
Insert into APP_USER_LOC (USER_NAME,LOCATION_CODE,LOCATION_DESC) values ('E0016','SLS014',null);
Insert into APP_USER_LOC (USER_NAME,LOCATION_CODE,LOCATION_DESC) values ('S0032','SLM006',null);
Insert into APP_USER_LOC (USER_NAME,LOCATION_CODE,LOCATION_DESC) values ('S0032','SLP006',null);
Insert into APP_USER_LOC (USER_NAME,LOCATION_CODE,LOCATION_DESC) values ('D0019','SLJ006',null);
Insert into APP_USER_LOC (USER_NAME,LOCATION_CODE,LOCATION_DESC) values ('D0019','SLL001',null);
Insert into APP_USER_LOC (USER_NAME,LOCATION_CODE,LOCATION_DESC) values ('D0019','SLP002',null);
Insert into APP_USER_LOC (USER_NAME,LOCATION_CODE,LOCATION_DESC) values ('I0009','SLA002',null);
Insert into APP_USER_LOC (USER_NAME,LOCATION_CODE,LOCATION_DESC) values ('I0009','SLD001',null);
Insert into APP_USER_LOC (USER_NAME,LOCATION_CODE,LOCATION_DESC) values ('I0009','SLK004',null);
Insert into APP_USER_LOC (USER_NAME,LOCATION_CODE,LOCATION_DESC) values ('I0009','SLM005',null);
Insert into APP_USER_LOC (USER_NAME,LOCATION_CODE,LOCATION_DESC) values ('I0009','SLM007',null);
Insert into APP_USER_LOC (USER_NAME,LOCATION_CODE,LOCATION_DESC) values ('I0009','SLM015',null);
Insert into APP_USER_LOC (USER_NAME,LOCATION_CODE,LOCATION_DESC) values ('M0018','SLD001',null);
Insert into APP_USER_LOC (USER_NAME,LOCATION_CODE,LOCATION_DESC) values ('M0018','SLM015',null);
Insert into APP_USER_LOC (USER_NAME,LOCATION_CODE,LOCATION_DESC) values ('A0030','SLK004',null);
Insert into APP_USER_LOC (USER_NAME,LOCATION_CODE,LOCATION_DESC) values ('A0030','SLM007',null);
Insert into APP_USER_LOC (USER_NAME,LOCATION_CODE,LOCATION_DESC) values ('A0033','SLM005',null);
Insert into APP_USER_LOC (USER_NAME,LOCATION_CODE,LOCATION_DESC) values ('Y0002','SLB006',null);
Insert into APP_USER_LOC (USER_NAME,LOCATION_CODE,LOCATION_DESC) values ('Y0002','SLP006',null);
Insert into APP_USER_LOC (USER_NAME,LOCATION_CODE,LOCATION_DESC) values ('A0071','SLS001',null);
Insert into APP_USER_LOC (USER_NAME,LOCATION_CODE,LOCATION_DESC) values ('R0007','SLB004',null);
Insert into APP_USER_LOC (USER_NAME,LOCATION_CODE,LOCATION_DESC) values ('Z0006','SLP007',null);
Insert into APP_USER_LOC (USER_NAME,LOCATION_CODE,LOCATION_DESC) values ('M0005','SLJ008',null);
Insert into APP_USER_LOC (USER_NAME,LOCATION_CODE,LOCATION_DESC) values ('M0005','SLM004',null);
Insert into APP_USER_LOC (USER_NAME,LOCATION_CODE,LOCATION_DESC) values ('M0005','SLP009',null);
Insert into APP_USER_LOC (USER_NAME,LOCATION_CODE,LOCATION_DESC) values ('M0005','SLS002',null);
Insert into APP_USER_LOC (USER_NAME,LOCATION_CODE,LOCATION_DESC) values ('M0005','SLS004',null);
Insert into APP_USER_LOC (USER_NAME,LOCATION_CODE,LOCATION_DESC) values ('M0005','SLS014',null);
Insert into APP_USER_LOC (USER_NAME,LOCATION_CODE,LOCATION_DESC) values ('M0005','SLT004',null);
Insert into APP_USER_LOC (USER_NAME,LOCATION_CODE,LOCATION_DESC) values ('M0005','SLY001',null);
Insert into APP_USER_LOC (USER_NAME,LOCATION_CODE,LOCATION_DESC) values ('A0012','SLJ008',null);
Insert into APP_USER_LOC (USER_NAME,LOCATION_CODE,LOCATION_DESC) values ('A0012','SLM004',null);
Insert into APP_USER_LOC (USER_NAME,LOCATION_CODE,LOCATION_DESC) values ('A0012','SLS014',null);
Insert into APP_USER_LOC (USER_NAME,LOCATION_CODE,LOCATION_DESC) values ('Y0003','SLB003',null);
Insert into APP_USER_LOC (USER_NAME,LOCATION_CODE,LOCATION_DESC) values ('Y0003','SLC001',null);
Insert into APP_USER_LOC (USER_NAME,LOCATION_CODE,LOCATION_DESC) values ('Y0003','SLK002',null);
Insert into APP_USER_LOC (USER_NAME,LOCATION_CODE,LOCATION_DESC) values ('Y0003','SLS006',null);
Insert into APP_USER_LOC (USER_NAME,LOCATION_CODE,LOCATION_DESC) values ('A0022','SLP009',null);
Insert into APP_USER_LOC (USER_NAME,LOCATION_CODE,LOCATION_DESC) values ('A0022','SLS002',null);
Insert into APP_USER_LOC (USER_NAME,LOCATION_CODE,LOCATION_DESC) values ('A0022','SLS004',null);
Insert into APP_USER_LOC (USER_NAME,LOCATION_CODE,LOCATION_DESC) values ('A0022','SLT004',null);
Insert into APP_USER_LOC (USER_NAME,LOCATION_CODE,LOCATION_DESC) values ('A0022','SLY001',null);
Insert into APP_USER_LOC (USER_NAME,LOCATION_CODE,LOCATION_DESC) values ('A0060','SLM005',null);
Insert into APP_USER_LOC (USER_NAME,LOCATION_CODE,LOCATION_DESC) values ('A0063','SLJ006',null);
Insert into APP_USER_LOC (USER_NAME,LOCATION_CODE,LOCATION_DESC) values ('A0063','SLL001',null);
Insert into APP_USER_LOC (USER_NAME,LOCATION_CODE,LOCATION_DESC) values ('A0063','SLP002',null);
Insert into APP_USER_LOC (USER_NAME,LOCATION_CODE,LOCATION_DESC) values ('H0023','SLB007',null);
Insert into APP_USER_LOC (USER_NAME,LOCATION_CODE,LOCATION_DESC) values ('H0023','SLD005',null);
Insert into APP_USER_LOC (USER_NAME,LOCATION_CODE,LOCATION_DESC) values ('H0023','SLJ001',null);
Insert into APP_USER_LOC (USER_NAME,LOCATION_CODE,LOCATION_DESC) values ('H0023','SLJ002',null);
Insert into APP_USER_LOC (USER_NAME,LOCATION_CODE,LOCATION_DESC) values ('H0023','SLS003',null);
--------------------------------------------------------
--  DDL for Index APP_USER_LOC_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "APP_USER_LOC_PK" ON "APP_USER_LOC" ("USER_NAME", "LOCATION_CODE") 
  ;
--------------------------------------------------------
--  Constraints for Table APP_USER_LOC
--------------------------------------------------------

  ALTER TABLE "APP_USER_LOC" MODIFY ("USER_NAME" NOT NULL ENABLE);
  ALTER TABLE "APP_USER_LOC" MODIFY ("LOCATION_CODE" NOT NULL ENABLE);
  ALTER TABLE "APP_USER_LOC" ADD CONSTRAINT "APP_USER_LOC_PK" PRIMARY KEY ("USER_NAME", "LOCATION_CODE") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table APP_USER_LOC
--------------------------------------------------------

  ALTER TABLE "APP_USER_LOC" ADD CONSTRAINT "APP_USER_LOC_APP_USER_ACC_FK1" FOREIGN KEY ("USER_NAME")
	  REFERENCES "APP_USER_ACCESS" ("USER_NAME") ON DELETE CASCADE ENABLE;
