--------------------------------------------------------
--  File created - Monday-October-07-2019   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table APP_USER_CUST_GROUP
--------------------------------------------------------

  CREATE TABLE "APP_USER_CUST_GROUP" 
   (	"USER_NAME" VARCHAR2(30), 
	"CUST_GROUP" VARCHAR2(20), 
	"CUST_GROUP_DESC" VARCHAR2(250)
   ) ;
REM INSERTING into APP_USER_CUST_GROUP
SET DEFINE OFF;
Insert into APP_USER_CUST_GROUP (USER_NAME,CUST_GROUP,CUST_GROUP_DESC) values ('R0042','GKAH0003',null);
Insert into APP_USER_CUST_GROUP (USER_NAME,CUST_GROUP,CUST_GROUP_DESC) values ('R0042','GKAI0001',null);
Insert into APP_USER_CUST_GROUP (USER_NAME,CUST_GROUP,CUST_GROUP_DESC) values ('R0042','GKAI0002',null);
Insert into APP_USER_CUST_GROUP (USER_NAME,CUST_GROUP,CUST_GROUP_DESC) values ('R0042','GKAR0001',null);
Insert into APP_USER_CUST_GROUP (USER_NAME,CUST_GROUP,CUST_GROUP_DESC) values ('R0042','GKAR0004',null);
Insert into APP_USER_CUST_GROUP (USER_NAME,CUST_GROUP,CUST_GROUP_DESC) values ('R0042','GKAY0001',null);
Insert into APP_USER_CUST_GROUP (USER_NAME,CUST_GROUP,CUST_GROUP_DESC) values ('B0001','GKAH0004',null);
Insert into APP_USER_CUST_GROUP (USER_NAME,CUST_GROUP,CUST_GROUP_DESC) values ('B0001','GKAI0001',null);
Insert into APP_USER_CUST_GROUP (USER_NAME,CUST_GROUP,CUST_GROUP_DESC) values ('B0001','GKAI0002',null);
Insert into APP_USER_CUST_GROUP (USER_NAME,CUST_GROUP,CUST_GROUP_DESC) values ('B0001','GKAL0005',null);
Insert into APP_USER_CUST_GROUP (USER_NAME,CUST_GROUP,CUST_GROUP_DESC) values ('B0001','GKAL0006',null);
Insert into APP_USER_CUST_GROUP (USER_NAME,CUST_GROUP,CUST_GROUP_DESC) values ('B0001','GKAR0004',null);
Insert into APP_USER_CUST_GROUP (USER_NAME,CUST_GROUP,CUST_GROUP_DESC) values ('F0018','GKAA0006',null);
Insert into APP_USER_CUST_GROUP (USER_NAME,CUST_GROUP,CUST_GROUP_DESC) values ('F0018','GKAA0007',null);
Insert into APP_USER_CUST_GROUP (USER_NAME,CUST_GROUP,CUST_GROUP_DESC) values ('F0018','GKAC0001',null);
Insert into APP_USER_CUST_GROUP (USER_NAME,CUST_GROUP,CUST_GROUP_DESC) values ('F0018','GKAG0004',null);
Insert into APP_USER_CUST_GROUP (USER_NAME,CUST_GROUP,CUST_GROUP_DESC) values ('F0018','GKAH0005',null);
Insert into APP_USER_CUST_GROUP (USER_NAME,CUST_GROUP,CUST_GROUP_DESC) values ('F0018','GKAL0003',null);
Insert into APP_USER_CUST_GROUP (USER_NAME,CUST_GROUP,CUST_GROUP_DESC) values ('H0010','GKAA0006',null);
Insert into APP_USER_CUST_GROUP (USER_NAME,CUST_GROUP,CUST_GROUP_DESC) values ('H0010','GKAA0007',null);
Insert into APP_USER_CUST_GROUP (USER_NAME,CUST_GROUP,CUST_GROUP_DESC) values ('H0010','GKAC0001',null);
Insert into APP_USER_CUST_GROUP (USER_NAME,CUST_GROUP,CUST_GROUP_DESC) values ('H0010','GKAG0004',null);
Insert into APP_USER_CUST_GROUP (USER_NAME,CUST_GROUP,CUST_GROUP_DESC) values ('H0010','GKAH0005',null);
Insert into APP_USER_CUST_GROUP (USER_NAME,CUST_GROUP,CUST_GROUP_DESC) values ('H0010','GKAL0003',null);
Insert into APP_USER_CUST_GROUP (USER_NAME,CUST_GROUP,CUST_GROUP_DESC) values ('I0009','GKAA0006',null);
Insert into APP_USER_CUST_GROUP (USER_NAME,CUST_GROUP,CUST_GROUP_DESC) values ('I0009','GKAA0007',null);
Insert into APP_USER_CUST_GROUP (USER_NAME,CUST_GROUP,CUST_GROUP_DESC) values ('I0009','GKAC0001',null);
Insert into APP_USER_CUST_GROUP (USER_NAME,CUST_GROUP,CUST_GROUP_DESC) values ('I0009','GKAG0004',null);
Insert into APP_USER_CUST_GROUP (USER_NAME,CUST_GROUP,CUST_GROUP_DESC) values ('I0009','GKAH0005',null);
Insert into APP_USER_CUST_GROUP (USER_NAME,CUST_GROUP,CUST_GROUP_DESC) values ('I0009','GKAL0003',null);
Insert into APP_USER_CUST_GROUP (USER_NAME,CUST_GROUP,CUST_GROUP_DESC) values ('M0009','GKAA0005',null);
Insert into APP_USER_CUST_GROUP (USER_NAME,CUST_GROUP,CUST_GROUP_DESC) values ('M0009','GKAD0001',null);
Insert into APP_USER_CUST_GROUP (USER_NAME,CUST_GROUP,CUST_GROUP_DESC) values ('M0009','GKAH0003',null);
Insert into APP_USER_CUST_GROUP (USER_NAME,CUST_GROUP,CUST_GROUP_DESC) values ('M0009','GKAL0003',null);
Insert into APP_USER_CUST_GROUP (USER_NAME,CUST_GROUP,CUST_GROUP_DESC) values ('M0009','GKAL0004',null);
Insert into APP_USER_CUST_GROUP (USER_NAME,CUST_GROUP,CUST_GROUP_DESC) values ('M0009','GKAN0001',null);
Insert into APP_USER_CUST_GROUP (USER_NAME,CUST_GROUP,CUST_GROUP_DESC) values ('M0009','GKAT0001',null);
Insert into APP_USER_CUST_GROUP (USER_NAME,CUST_GROUP,CUST_GROUP_DESC) values ('M0012','GKAC0001',null);
Insert into APP_USER_CUST_GROUP (USER_NAME,CUST_GROUP,CUST_GROUP_DESC) values ('M0012','GKAH0004',null);
Insert into APP_USER_CUST_GROUP (USER_NAME,CUST_GROUP,CUST_GROUP_DESC) values ('M0012','GKAH0005',null);
Insert into APP_USER_CUST_GROUP (USER_NAME,CUST_GROUP,CUST_GROUP_DESC) values ('P0002','GKAA0005',null);
Insert into APP_USER_CUST_GROUP (USER_NAME,CUST_GROUP,CUST_GROUP_DESC) values ('P0002','GKAD0001',null);
Insert into APP_USER_CUST_GROUP (USER_NAME,CUST_GROUP,CUST_GROUP_DESC) values ('P0002','GKAL0004',null);
Insert into APP_USER_CUST_GROUP (USER_NAME,CUST_GROUP,CUST_GROUP_DESC) values ('P0002','GKAN0001',null);
Insert into APP_USER_CUST_GROUP (USER_NAME,CUST_GROUP,CUST_GROUP_DESC) values ('P0002','GKAR0001',null);
Insert into APP_USER_CUST_GROUP (USER_NAME,CUST_GROUP,CUST_GROUP_DESC) values ('P0002','GKAS0001',null);
Insert into APP_USER_CUST_GROUP (USER_NAME,CUST_GROUP,CUST_GROUP_DESC) values ('P0002','GKAS0005',null);
Insert into APP_USER_CUST_GROUP (USER_NAME,CUST_GROUP,CUST_GROUP_DESC) values ('P0002','GKAT0001',null);
Insert into APP_USER_CUST_GROUP (USER_NAME,CUST_GROUP,CUST_GROUP_DESC) values ('P0002','GKAY0001',null);
Insert into APP_USER_CUST_GROUP (USER_NAME,CUST_GROUP,CUST_GROUP_DESC) values ('P0006','GKAH0004',null);
Insert into APP_USER_CUST_GROUP (USER_NAME,CUST_GROUP,CUST_GROUP_DESC) values ('P0006','GKAI0001',null);
Insert into APP_USER_CUST_GROUP (USER_NAME,CUST_GROUP,CUST_GROUP_DESC) values ('P0006','GKAI0002',null);
Insert into APP_USER_CUST_GROUP (USER_NAME,CUST_GROUP,CUST_GROUP_DESC) values ('P0006','GKAL0005',null);
Insert into APP_USER_CUST_GROUP (USER_NAME,CUST_GROUP,CUST_GROUP_DESC) values ('P0006','GKAL0006',null);
Insert into APP_USER_CUST_GROUP (USER_NAME,CUST_GROUP,CUST_GROUP_DESC) values ('P0006','GKAR0004',null);
Insert into APP_USER_CUST_GROUP (USER_NAME,CUST_GROUP,CUST_GROUP_DESC) values ('R0003','GKAA0006',null);
Insert into APP_USER_CUST_GROUP (USER_NAME,CUST_GROUP,CUST_GROUP_DESC) values ('R0003','GKAA0007',null);
Insert into APP_USER_CUST_GROUP (USER_NAME,CUST_GROUP,CUST_GROUP_DESC) values ('R0003','GKAL0005',null);
Insert into APP_USER_CUST_GROUP (USER_NAME,CUST_GROUP,CUST_GROUP_DESC) values ('R0003','GKAL0006',null);
Insert into APP_USER_CUST_GROUP (USER_NAME,CUST_GROUP,CUST_GROUP_DESC) values ('R0003','GKAS0005',null);
Insert into APP_USER_CUST_GROUP (USER_NAME,CUST_GROUP,CUST_GROUP_DESC) values ('W0001','GKAA0005',null);
Insert into APP_USER_CUST_GROUP (USER_NAME,CUST_GROUP,CUST_GROUP_DESC) values ('W0001','GKAA0006',null);
Insert into APP_USER_CUST_GROUP (USER_NAME,CUST_GROUP,CUST_GROUP_DESC) values ('W0001','GKAA0007',null);
Insert into APP_USER_CUST_GROUP (USER_NAME,CUST_GROUP,CUST_GROUP_DESC) values ('W0001','GKAC0001',null);
Insert into APP_USER_CUST_GROUP (USER_NAME,CUST_GROUP,CUST_GROUP_DESC) values ('W0001','GKAD0001',null);
Insert into APP_USER_CUST_GROUP (USER_NAME,CUST_GROUP,CUST_GROUP_DESC) values ('W0001','GKAE0001',null);
Insert into APP_USER_CUST_GROUP (USER_NAME,CUST_GROUP,CUST_GROUP_DESC) values ('W0001','GKAG0004',null);
Insert into APP_USER_CUST_GROUP (USER_NAME,CUST_GROUP,CUST_GROUP_DESC) values ('W0001','GKAH0003',null);
Insert into APP_USER_CUST_GROUP (USER_NAME,CUST_GROUP,CUST_GROUP_DESC) values ('W0001','GKAH0004',null);
Insert into APP_USER_CUST_GROUP (USER_NAME,CUST_GROUP,CUST_GROUP_DESC) values ('W0001','GKAI0001',null);
Insert into APP_USER_CUST_GROUP (USER_NAME,CUST_GROUP,CUST_GROUP_DESC) values ('W0001','GKAI0002',null);
Insert into APP_USER_CUST_GROUP (USER_NAME,CUST_GROUP,CUST_GROUP_DESC) values ('W0001','GKAL0003',null);
Insert into APP_USER_CUST_GROUP (USER_NAME,CUST_GROUP,CUST_GROUP_DESC) values ('W0001','GKAL0004',null);
Insert into APP_USER_CUST_GROUP (USER_NAME,CUST_GROUP,CUST_GROUP_DESC) values ('W0001','GKAL0005',null);
Insert into APP_USER_CUST_GROUP (USER_NAME,CUST_GROUP,CUST_GROUP_DESC) values ('W0001','GKAL0006',null);
Insert into APP_USER_CUST_GROUP (USER_NAME,CUST_GROUP,CUST_GROUP_DESC) values ('W0001','GKAN0001',null);
Insert into APP_USER_CUST_GROUP (USER_NAME,CUST_GROUP,CUST_GROUP_DESC) values ('W0001','GKAR0001',null);
Insert into APP_USER_CUST_GROUP (USER_NAME,CUST_GROUP,CUST_GROUP_DESC) values ('W0001','GKAR0004',null);
Insert into APP_USER_CUST_GROUP (USER_NAME,CUST_GROUP,CUST_GROUP_DESC) values ('W0001','GKAS0001',null);
Insert into APP_USER_CUST_GROUP (USER_NAME,CUST_GROUP,CUST_GROUP_DESC) values ('W0001','GKAS0005',null);
Insert into APP_USER_CUST_GROUP (USER_NAME,CUST_GROUP,CUST_GROUP_DESC) values ('W0001','GKAT0001',null);
Insert into APP_USER_CUST_GROUP (USER_NAME,CUST_GROUP,CUST_GROUP_DESC) values ('W0001','GKAY0001',null);
Insert into APP_USER_CUST_GROUP (USER_NAME,CUST_GROUP,CUST_GROUP_DESC) values ('W0001','GKAH0005',null);
Insert into APP_USER_CUST_GROUP (USER_NAME,CUST_GROUP,CUST_GROUP_DESC) values ('L0003','GKAD0001',null);
Insert into APP_USER_CUST_GROUP (USER_NAME,CUST_GROUP,CUST_GROUP_DESC) values ('L0003','GKAL0004',null);
Insert into APP_USER_CUST_GROUP (USER_NAME,CUST_GROUP,CUST_GROUP_DESC) values ('L0003','GKAN0001',null);
Insert into APP_USER_CUST_GROUP (USER_NAME,CUST_GROUP,CUST_GROUP_DESC) values ('L0003','GKAS0005',null);
Insert into APP_USER_CUST_GROUP (USER_NAME,CUST_GROUP,CUST_GROUP_DESC) values ('L0003','GKAT0001',null);
Insert into APP_USER_CUST_GROUP (USER_NAME,CUST_GROUP,CUST_GROUP_DESC) values ('S0023','GKAA0005',null);
Insert into APP_USER_CUST_GROUP (USER_NAME,CUST_GROUP,CUST_GROUP_DESC) values ('S0023','GKAC0001',null);
Insert into APP_USER_CUST_GROUP (USER_NAME,CUST_GROUP,CUST_GROUP_DESC) values ('S0023','GKAH0004',null);
Insert into APP_USER_CUST_GROUP (USER_NAME,CUST_GROUP,CUST_GROUP_DESC) values ('S0023','GKAN0001',null);
Insert into APP_USER_CUST_GROUP (USER_NAME,CUST_GROUP,CUST_GROUP_DESC) values ('S0023','GKAT0001',null);
Insert into APP_USER_CUST_GROUP (USER_NAME,CUST_GROUP,CUST_GROUP_DESC) values ('S0023','GKAD0001',null);
Insert into APP_USER_CUST_GROUP (USER_NAME,CUST_GROUP,CUST_GROUP_DESC) values ('S0023','GKAH0003',null);
Insert into APP_USER_CUST_GROUP (USER_NAME,CUST_GROUP,CUST_GROUP_DESC) values ('S0023','GKAH0005',null);
Insert into APP_USER_CUST_GROUP (USER_NAME,CUST_GROUP,CUST_GROUP_DESC) values ('S0023','GKAL0003',null);
Insert into APP_USER_CUST_GROUP (USER_NAME,CUST_GROUP,CUST_GROUP_DESC) values ('S0023','GKAL0004',null);
Insert into APP_USER_CUST_GROUP (USER_NAME,CUST_GROUP,CUST_GROUP_DESC) values ('O0001','GKAA0005',null);
Insert into APP_USER_CUST_GROUP (USER_NAME,CUST_GROUP,CUST_GROUP_DESC) values ('O0001','GKAA0006',null);
Insert into APP_USER_CUST_GROUP (USER_NAME,CUST_GROUP,CUST_GROUP_DESC) values ('O0001','GKAA0007',null);
Insert into APP_USER_CUST_GROUP (USER_NAME,CUST_GROUP,CUST_GROUP_DESC) values ('O0001','GKAC0001',null);
Insert into APP_USER_CUST_GROUP (USER_NAME,CUST_GROUP,CUST_GROUP_DESC) values ('O0001','GKAD0001',null);
Insert into APP_USER_CUST_GROUP (USER_NAME,CUST_GROUP,CUST_GROUP_DESC) values ('O0001','GKAG0004',null);
Insert into APP_USER_CUST_GROUP (USER_NAME,CUST_GROUP,CUST_GROUP_DESC) values ('O0001','GKAH0003',null);
Insert into APP_USER_CUST_GROUP (USER_NAME,CUST_GROUP,CUST_GROUP_DESC) values ('O0001','GKAH0004',null);
Insert into APP_USER_CUST_GROUP (USER_NAME,CUST_GROUP,CUST_GROUP_DESC) values ('O0001','GKAH0005',null);
Insert into APP_USER_CUST_GROUP (USER_NAME,CUST_GROUP,CUST_GROUP_DESC) values ('O0001','GKAI0001',null);
Insert into APP_USER_CUST_GROUP (USER_NAME,CUST_GROUP,CUST_GROUP_DESC) values ('O0001','GKAI0002',null);
Insert into APP_USER_CUST_GROUP (USER_NAME,CUST_GROUP,CUST_GROUP_DESC) values ('O0001','GKAL0003',null);
Insert into APP_USER_CUST_GROUP (USER_NAME,CUST_GROUP,CUST_GROUP_DESC) values ('O0001','GKAL0004',null);
Insert into APP_USER_CUST_GROUP (USER_NAME,CUST_GROUP,CUST_GROUP_DESC) values ('O0001','GKAL0005',null);
Insert into APP_USER_CUST_GROUP (USER_NAME,CUST_GROUP,CUST_GROUP_DESC) values ('O0001','GKAL0006',null);
Insert into APP_USER_CUST_GROUP (USER_NAME,CUST_GROUP,CUST_GROUP_DESC) values ('O0001','GKAN0001',null);
Insert into APP_USER_CUST_GROUP (USER_NAME,CUST_GROUP,CUST_GROUP_DESC) values ('O0001','GKAR0001',null);
Insert into APP_USER_CUST_GROUP (USER_NAME,CUST_GROUP,CUST_GROUP_DESC) values ('O0001','GKAR0004',null);
Insert into APP_USER_CUST_GROUP (USER_NAME,CUST_GROUP,CUST_GROUP_DESC) values ('O0001','GKAS0005',null);
Insert into APP_USER_CUST_GROUP (USER_NAME,CUST_GROUP,CUST_GROUP_DESC) values ('O0001','GKAT0001',null);
Insert into APP_USER_CUST_GROUP (USER_NAME,CUST_GROUP,CUST_GROUP_DESC) values ('O0001','GKAY0001',null);
Insert into APP_USER_CUST_GROUP (USER_NAME,CUST_GROUP,CUST_GROUP_DESC) values ('R0017','GKAA0005',null);
Insert into APP_USER_CUST_GROUP (USER_NAME,CUST_GROUP,CUST_GROUP_DESC) values ('R0017','GKAB0001',null);
Insert into APP_USER_CUST_GROUP (USER_NAME,CUST_GROUP,CUST_GROUP_DESC) values ('R0017','GKAR0001',null);
Insert into APP_USER_CUST_GROUP (USER_NAME,CUST_GROUP,CUST_GROUP_DESC) values ('R0017','GKAS0001',null);
Insert into APP_USER_CUST_GROUP (USER_NAME,CUST_GROUP,CUST_GROUP_DESC) values ('R0017','GKAY0001',null);
--------------------------------------------------------
--  DDL for Index APP_USER_CUST_GROUP_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "APP_USER_CUST_GROUP_PK" ON "APP_USER_CUST_GROUP" ("USER_NAME", "CUST_GROUP") 
  ;
--------------------------------------------------------
--  Constraints for Table APP_USER_CUST_GROUP
--------------------------------------------------------

  ALTER TABLE "APP_USER_CUST_GROUP" MODIFY ("USER_NAME" NOT NULL ENABLE);
  ALTER TABLE "APP_USER_CUST_GROUP" MODIFY ("CUST_GROUP" NOT NULL ENABLE);
  ALTER TABLE "APP_USER_CUST_GROUP" ADD CONSTRAINT "APP_USER_CUST_GROUP_PK" PRIMARY KEY ("USER_NAME", "CUST_GROUP") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table APP_USER_CUST_GROUP
--------------------------------------------------------

  ALTER TABLE "APP_USER_CUST_GROUP" ADD CONSTRAINT "APP_USER_CUST_GROUP_APP_U_FK1" FOREIGN KEY ("USER_NAME")
	  REFERENCES "APP_USER_ACCESS" ("USER_NAME") ON DELETE CASCADE ENABLE;
