SET DEFINE OFF;

REM TEST SCENARIO DCV Resubmit - Distributor
REM DCVH_ID = 1012

DELETE WF_TASK WHERE DCVH_ID = 1012;
DELETE DCV_REQUEST WHERE DCVH_ID = 1012;
exec dbms_output.put_line('INSERTING into DCV_REQUEST');

alter table dcv_request disable all triggers;
Insert into DCV_REQUEST (DCVH_ID,DCVH_NO_DCV,DCVH_STATUS,DCVH_LAST_STEP,DCVH_CURRENT_STEP,MODIFIED_DT,MODIFIED_BY,DCVH_CUST_CODE,DCVH_CUST_NAME,DCVH_COMPANY,DCVH_NO_PC,DCVH_KEY_PC,DCVH_NO_PP,DCVH_NO_PP_ID,DCVH_PERIODE_DCV_START,DCVH_PERIODE_DCV_END,DCVH_PC_KATEGORI,DCVH_PC_TIPE,DCVH_PERIODE_PC_START,DCVH_PERIODE_PC_END,DCVH_SUBMIT_TIME,DCVH_SELISIH_HARI,DCVH_VALUE,DCVH_APPV_VALUE,DCVH_KETR_KWITANSI,DCVH_METODE_BAYAR,DCVH_REGION,DCVH_AREA,DCVH_LOCATION) values (1012,'201909000028','ON-PROGRESS',null,'Tunggu Proses Sales',to_date('30-SEP-19','DD-MON-RR'),'Disti2','Disti2','Disti2','I','I0319000119','27080356180124','DIA18030062',1911,to_date('01-MAR-19','DD-MON-RR'),to_date('31-MAR-19','DD-MON-RR'),'I03',null,to_date('31-JAN-19','DD-MON-RR'),to_date('15-MAR-19','DD-MON-RR'),to_date('07-APR-19','DD-MON-RR'),199,null,null,null,'PO',null,null,null);
alter table dcv_request enable all triggers;

SREM INSERTING into WF_TASK
SET DEFINE OFF;
Insert into WF_TASK (ID,NO_DCV,TASK_TYPE,ASSIGN_TIME,BAGIAN,ROLE_ASSIGNED,PROGRESS_STATUS,NODECODE,PREV_TASK,TAHAPAN,DECISION,EXECSCRIPT,NEXT_TASK,NEXT_NODE,NOTE,PRIME_ROUTE,RETURN_TASK,PROCESS_BY,PROCESS_TIME,SLA,ROLLBACK_TASK,ROLLBACK_ID,BEBAN_SLA,SORTING_TAG,TARGET_SELESAI,DCVH_ID) values (1015,'201909000028','Start',SYSDATE-6,'Distributor',null,'DONE','D0',null,'Sudah submit DCV Request',1,null,1016,'SL1',null,'Y',null,'Disti2',SYSDATE-6,null,null,null,null,null,null,1012);
Insert into WF_TASK (ID,NO_DCV,TASK_TYPE,ASSIGN_TIME,BAGIAN,ROLE_ASSIGNED,PROGRESS_STATUS,NODECODE,PREV_TASK,TAHAPAN,DECISION,EXECSCRIPT,NEXT_TASK,NEXT_NODE,NOTE,PRIME_ROUTE,RETURN_TASK,PROCESS_BY,PROCESS_TIME,SLA,ROLLBACK_TASK,ROLLBACK_ID,BEBAN_SLA,SORTING_TAG,TARGET_SELESAI,DCVH_ID) values (1016,'201909000028','Human',SYSDATE-6,'Sales',null,'DONE','SL1',1015,'Ditolak - Sales',2,null,1129,'D1',null,'Y',null,'Sales1',SYSDATE-5,null,null,null,null,null,null,1012);
Insert into WF_TASK (ID,NO_DCV,TASK_TYPE,ASSIGN_TIME,BAGIAN,ROLE_ASSIGNED,PROGRESS_STATUS,NODECODE,PREV_TASK,TAHAPAN,DECISION,EXECSCRIPT,NEXT_TASK,NEXT_NODE,NOTE,PRIME_ROUTE,RETURN_TASK,PROCESS_BY,PROCESS_TIME,SLA,ROLLBACK_TASK,ROLLBACK_ID,BEBAN_SLA,SORTING_TAG,TARGET_SELESAI,DCVH_ID) values (1129,'201909000028','Human',SYSDATE-5,'Distributor',null,'DONE','D1',1016,'Submit DCV - Distributor',1,null,1130,'SCRP-1',null,'Y','Y','Disti2',SYSDATE-4,null,null,null,null,'A',null,1012);
Insert into WF_TASK (ID,NO_DCV,TASK_TYPE,ASSIGN_TIME,BAGIAN,ROLE_ASSIGNED,PROGRESS_STATUS,NODECODE,PREV_TASK,TAHAPAN,DECISION,EXECSCRIPT,NEXT_TASK,NEXT_NODE,NOTE,PRIME_ROUTE,RETURN_TASK,PROCESS_BY,PROCESS_TIME,SLA,ROLLBACK_TASK,ROLLBACK_ID,BEBAN_SLA,SORTING_TAG,TARGET_SELESAI,DCVH_ID) values (1130,'201909000028','Script',SYSDATE-4,'Distributor',null,'DONE','SCRP-1',1129,'Submit ulang DCV - Distributor',1,'wfproc_pkg.back2_sales_tc',1131,'SL1',null,'Y',null,'Disti2',SYSDATE-3,null,null,null,null,'A',null,1012);
Insert into WF_TASK (ID,NO_DCV,TASK_TYPE,ASSIGN_TIME,BAGIAN,ROLE_ASSIGNED,PROGRESS_STATUS,NODECODE,PREV_TASK,TAHAPAN,DECISION,EXECSCRIPT,NEXT_TASK,NEXT_NODE,NOTE,PRIME_ROUTE,RETURN_TASK,PROCESS_BY,PROCESS_TIME,SLA,ROLLBACK_TASK,ROLLBACK_ID,BEBAN_SLA,SORTING_TAG,TARGET_SELESAI,DCVH_ID) values (1131,'201909000028','Human',SYSDATE-3,'Sales',null,'DONE','SL1',1130,'Disetujui - Sales',1,null,1132,'TC1',null,'Y',null,'Sales1',SYSDATE-2,null,null,null,null,'A',null,1012);
Insert into WF_TASK (ID,NO_DCV,TASK_TYPE,ASSIGN_TIME,BAGIAN,ROLE_ASSIGNED,PROGRESS_STATUS,NODECODE,PREV_TASK,TAHAPAN,DECISION,EXECSCRIPT,NEXT_TASK,NEXT_NODE,NOTE,PRIME_ROUTE,RETURN_TASK,PROCESS_BY,PROCESS_TIME,SLA,ROLLBACK_TASK,ROLLBACK_ID,BEBAN_SLA,SORTING_TAG,TARGET_SELESAI,DCVH_ID) values (1132,'201909000028','Human',SYSDATE-2,'TC',null,'DONE','TC1',1131,'Ditolak - TC',2,null,1133,'D1',null,'Y',null,'TC1',SYSDATE-1,null,null,null,null,'A',null,1012);
Insert into WF_TASK (ID,NO_DCV,TASK_TYPE,ASSIGN_TIME,BAGIAN,ROLE_ASSIGNED,PROGRESS_STATUS,NODECODE,PREV_TASK,TAHAPAN,DECISION,EXECSCRIPT,NEXT_TASK,NEXT_NODE,NOTE,PRIME_ROUTE,RETURN_TASK,PROCESS_BY,PROCESS_TIME,SLA,ROLLBACK_TASK,ROLLBACK_ID,BEBAN_SLA,SORTING_TAG,TARGET_SELESAI,DCVH_ID) values (1133,'201909000028','Human',SYSDATE-1,'Distributor',null,'WAIT','D1',1132,'Tunggu proses distributor',null,null,null,null,null,'Y','Y',null,null,null,null,null,null,'A',null,1012);

COMMIT;

DECLARE
  vResponse VARCHAR2(300);
  res NUMBER;
BEGIN
  vResponse := wf_pkg.post_action ('201909000028', 'D1', 1, 'Disti2') ;  -- distributor submit dcv
  dbms_output.put_line('Hasilnya:');
  dbms_output.put_line(vResponse);
END;
/
COMMIT;
