-- Generated by Oracle SQL Developer Data Modeler 18.1.0.082.1035
--   at:        2019-04-26 20:10:36 ICT
--   site:      Oracle Database 12c
--   type:      Oracle Database 12c

DROP TABLE dcv_documents CASCADE CONSTRAINTS;
CREATE TABLE dcv_documents (
  id              INTEGER NOT NULL,
  dcvh_id         INTEGER NOT NULL,
  doc_type        VARCHAR2(25 CHAR),
  doc_no          VARCHAR2(25 CHAR),
  doc_date        DATE,
  upload_time     DATE,
  upload_by       VARCHAR2(30 CHAR),
  download_addr   VARCHAR2(500 CHAR),
  modified_by     VARCHAR2(25 CHAR),
  modified_dt     DATE
);

COMMENT ON COLUMN dcv_documents.doc_type IS
    'BA = Berita Acara
RF = Rekap Faktur
KW = Kwitansi
FP = Faktur Pajak
RK = No Resi Kwitansi
BP = No Bukti Potong Pph';

CREATE INDEX dcv_document_no_idx ON
    dcv_documents (
        doc_type ASC,
        doc_no  ASC );

ALTER TABLE dcv_documents ADD CONSTRAINT files_pk PRIMARY KEY ( id );

DROP TABLE dcv_number CASCADE CONSTRAINTS;
CREATE TABLE dcv_number (
    period        INTEGER NOT NULL,
    lastnum       INTEGER NOT NULL,
    modified_dt   DATE
);

ALTER TABLE dcv_number ADD CONSTRAINT dcv_number_pk PRIMARY KEY ( period );

DROP TABLE dcv_privs CASCADE CONSTRAINTS;
CREATE TABLE dcv_privs (
  id          INTEGER NOT NULL,
  priv_name   VARCHAR2(50 CHAR),
  descr       VARCHAR2(200 CHAR),
  priv_type   VARCHAR2(20 CHAR),
  ref_id      INTEGER
);
ALTER TABLE dcv_privs ADD CONSTRAINT dcv_privs_pk PRIMARY KEY ( id );
CREATE INDEX dcv_privs_name_idx ON dcv_privs (priv_type, priv_name);


DROP TABLE dcv_request CASCADE CONSTRAINTS;
CREATE TABLE dcv_request (
  dcvh_id                  INTEGER NOT NULL,
  dcvh_cust_code           VARCHAR2(100 CHAR) NOT NULL,
  dcvh_cust_name           VARCHAR2(200 CHAR),
  dcvh_company             VARCHAR2(3 CHAR) NOT NULL,
  dcvh_no_pc               VARCHAR2(100 CHAR) NOT NULL,
  dcvh_key_pc              VARCHAR2(14 CHAR) NOT NULL,
  dcvh_no_pp               VARCHAR2(100 CHAR),
  dcvh_no_pp_id            INTEGER,
  dcvh_periode_dcv_start   DATE NOT NULL,
  dcvh_periode_dcv_end     DATE,
  dcvh_pc_kategori         VARCHAR2(5),
  dcvh_pc_tipe             VARCHAR2(50),
  dcvh_periode_pc_start    DATE,
  dcvh_periode_pc_end      DATE,
  dcvh_no_dcv              VARCHAR2(15 CHAR),
  dcvh_region              VARCHAR2(30 CHAR),
  dcvh_area                VARCHAR2(60 CHAR),
  dcvh_location            VARCHAR2(100 CHAR),
  dcvh_submit_time         DATE,
  dcvh_selisih_hari        INTEGER,
  dcvh_value               NUMBER DEFAULT 0,
  dcvh_appv_value          NUMBER DEFAULT 0,
  dcvh_ketr_kwitansi       VARCHAR2(500 CHAR),
  dcvh_metode_bayar        VARCHAR2(5 CHAR),
  dcvh_status              VARCHAR2(30 CHAR),
  dcvh_last_step           VARCHAR2(60 CHAR),
  dcvh_current_step        VARCHAR2(60 CHAR),
  modified_dt              DATE,
  modified_by              VARCHAR2(50 CHAR)
);

COMMENT ON COLUMN dcv_request.dcvh_no_pc IS
    'pppc:proposal:confirm_no + addendum_ke';
COMMENT ON COLUMN dcv_request.dcvh_key_pc IS
    'pppc:proposal:report_run_number';
COMMENT ON COLUMN dcv_request.dcvh_selisih_hari IS
    'selisih hari pc end-dt sampai tgl request';
COMMENT ON COLUMN dcv_request.dcvh_value IS
    'total nilai request';
COMMENT ON COLUMN dcv_request.dcvh_appv_value IS
    'total nilai approve';
COMMENT ON COLUMN dcv_request.dcvh_ketr_kwitansi IS
    'ambil dari PO. Untuk kasus PO pc tambahan/pengganti, ambil PO pc asli';
COMMENT ON COLUMN dcv_request.dcvh_metode_bayar IS
    'PO / CM';
COMMENT ON COLUMN dcv_request.dcvh_status IS
    'CANCEL, ON-PROCESS, PAID, ROLLBACK';
CREATE UNIQUE INDEX dcv_no_idx ON
    dcv_request (dcvh_no_dcv ASC );

ALTER TABLE dcv_request ADD CONSTRAINT request_hdr_pk PRIMARY KEY ( dcvh_id );

DROP TABLE dcv_role CASCADE CONSTRAINTS;
CREATE TABLE dcv_role (
    role_code   VARCHAR2(30 CHAR) NOT NULL,
    role_name   VARCHAR2(100 CHAR),
    role_type   VARCHAR2(15 CHAR),
    bagian      VARCHAR2(20 CHAR)
);
ALTER TABLE dcv_role ADD CONSTRAINT dcv_role_pk PRIMARY KEY ( role_code );

DROP TABLE dcv_user_access CASCADE CONSTRAINTS;
CREATE TABLE dcv_user_access (
    id                   INTEGER NOT NULL,
    user_name            VARCHAR2(30 CHAR) NOT NULL,
    user_initial         VARCHAR2(3 CHAR) NOT NULL,
    password             VARCHAR2(50 CHAR),
    full_name            VARCHAR2(100 CHAR),
    descr                VARCHAR2(100 CHAR),
    title                VARCHAR2(100 CHAR),
    contact_no           VARCHAR2(40 CHAR),
    company_id           VARCHAR2(5 CHAR),
    active_period_from   DATE,
    active_period_to     DATE,
    user_type            VARCHAR2(20 CHAR),
    user_division        VARCHAR2(20 CHAR),
    direct_spv           VARCHAR2(30 CHAR),
    direct_spv_id        INTEGER,
    cust_auth_flag       VARCHAR2(20 CHAR),
    email_addr           VARCHAR2(100 CHAR)
);
ALTER TABLE dcv_user_access ADD CONSTRAINT dcv_user_access_pk PRIMARY KEY ( id );
ALTER TABLE dcv_user_access ADD CONSTRAINT dcv_username_un UNIQUE ( user_name );

DROP TABLE dcv_user_auth_mapping CASCADE CONSTRAINTS;
CREATE TABLE dcv_user_auth_mapping (
    id          INTEGER NOT NULL,
    pp_no       VARCHAR2(100 CHAR),
    pc_no       VARCHAR2(100 CHAR),
    user_id     INTEGER,
    user_name   VARCHAR2(100 CHAR),
    user_type   VARCHAR2(15 CHAR)
);
ALTER TABLE dcv_user_auth_mapping ADD CONSTRAINT dcv_user_auth_mapping_pk PRIMARY KEY ( id );

DROP TABLE dcv_user_role CASCADE CONSTRAINTS;
CREATE TABLE dcv_user_role (
    user_id     INTEGER NOT NULL,
    role_code   VARCHAR2(30 CHAR) NOT NULL
);
ALTER TABLE dcv_user_role ADD CONSTRAINT dcv_user_role_pk PRIMARY KEY ( user_id,role_code );

DROP TABLE disposisi CASCADE CONSTRAINTS;
CREATE TABLE disposisi   (
  dcvh_id          INTEGER NOT NULL,
  disposisi_type   VARCHAR2(10 CHAR),
  beban_sla        VARCHAR2(30 CHAR),
  hold_status      VARCHAR2(10 CHAR),
  start_dt         DATE,
  release_dt       DATE,
  note             VARCHAR2(500 CHAR)
);

COMMENT ON COLUMN disposisi.disposisi_type IS
    'BAYAR / HOLD';
COMMENT ON COLUMN disposisi.beban_sla IS
    'bagian yg menanggung sla';
COMMENT ON COLUMN disposisi.hold_status IS
    'HOLD / RELEASE';

ALTER TABLE disposisi ADD CONSTRAINT disposisi_pk PRIMARY KEY ( dcvh_id );

DROP TABLE dokumen_realisasi CASCADE CONSTRAINTS;
CREATE TABLE dokumen_realisasi (
  id                  INTEGER NOT NULL,
  dcvh_id             INTEGER NOT NULL,
  tahapan_realisasi   VARCHAR2(20 CHAR),
  doc_no              VARCHAR2(50 CHAR),
  doc_dt              DATE,
  descr               VARCHAR2(200 CHAR),
  trx_value           NUMBER,
  remaining_val       NUMBER,
  create_by           VARCHAR2(30 CHAR),
  create_dt           DATE,
  modified_by         VARCHAR2(30 CHAR),
  modified_dt         DATE
);
COMMENT ON COLUMN dokumen_realisasi.tahapan_realisasi IS
    'PO / GR / INVOICE / PAYMENT / ARAP NETTING';

ALTER TABLE dokumen_realisasi ADD CONSTRAINT dokumen_realisasi_pk PRIMARY KEY ( id );


DROP TABLE holiday CASCADE CONSTRAINTS;
CREATE TABLE holiday (
    id            INTEGER NOT NULL,
    tgl_libur     DATE,
    description   VARCHAR2(50 CHAR)
);

ALTER TABLE holiday ADD CONSTRAINT holiday_pk PRIMARY KEY ( id );

DROP TABLE parameter CASCADE CONSTRAINTS;
CREATE TABLE parameter (
    id      INTEGER NOT NULL,
    title   VARCHAR2(60 CHAR),
    value   VARCHAR2(60 CHAR),
    descr   VARCHAR2(120 CHAR)
);

ALTER TABLE parameter ADD CONSTRAINT parameter_pk PRIMARY KEY ( id );

DROP TABLE request_dtl CASCADE CONSTRAINTS;
CREATE TABLE request_dtl (
  dcvl_id                    INTEGER NOT NULL,
  dcvh_id                    INTEGER NOT NULL,
  dcvl_promo_product_id      INTEGER,
  dcvl_prod_class            VARCHAR2(40 CHAR),
  dcvl_prod_class_desc       VARCHAR2(100 CHAR),
  dcvl_prod_brand            VARCHAR2(40 CHAR),
  dcvl_prod_brand_desc       VARCHAR2(100 CHAR),
  dcvl_prod_ext              VARCHAR2(40 CHAR),
  dcvl_prod_ext_desc         VARCHAR2(100 CHAR),
  dcvl_prod_packaging        VARCHAR2(40 CHAR),
  dcvl_prod_packaging_desc   VARCHAR2(100 CHAR),
  dcvl_prod_variant          VARCHAR2(40 CHAR),
  dcvl_prod_variant_desc     VARCHAR2(100 CHAR),
  dcvl_prod_item             VARCHAR2(40 CHAR),
  dcvl_prod_item_desc        VARCHAR2(100 CHAR),
  dcvl_qty                   INTEGER,
  dcvl_uom                   VARCHAR2(15 CHAR),
  dcvl_val_exc               NUMBER DEFAULT 0,
  dcvl_catatan_distributor   VARCHAR2(200 CHAR),
  dcvl_appv_val_exc          NUMBER DEFAULT 0,
  dcvl_ppn_code              VARCHAR2(25 CHAR),
  dcvl_ppn_val               NUMBER,
  dcvl_pph_code              CHAR(25 CHAR),
  dcvl_pph_val               NUMBER DEFAULT 0,
  dcvl_total_val_appv_inc    NUMBER,
  dcvl_selisih               NUMBER,
  dcvl_catatan_tc            VARCHAR2(500 CHAR),
  modified_dt                DATE,
  modified_by                VARCHAR2(50 CHAR)
);

ALTER TABLE request_dtl ADD CONSTRAINT request_dtl_pk PRIMARY KEY ( dcvl_id );

DROP TABLE role_privs CASCADE CONSTRAINTS;
CREATE TABLE role_privs (
    role_code   VARCHAR2(30 CHAR) NOT NULL,
    priv_id     INTEGER NOT NULL
);
ALTER TABLE role_privs ADD CONSTRAINT role_privs_pk PRIMARY KEY ( role_code, priv_id );

DROP TABLE tc_approval CASCADE CONSTRAINTS;
CREATE TABLE tc_approval (
  id                             INTEGER NOT NULL,
  dcvl_id                        INTEGER NOT NULL,
  no_po                          VARCHAR2(50 CHAR),
  line_po                        INTEGER,
  no_pr                          VARCHAR2(50 CHAR),
  line_pr                        INTEGER,
  pc_pengganti                   VARCHAR2(100 CHAR),
  pc_pengganti_promo_produk_id   INTEGER,
  pc_tambahan                    VARCHAR2(100 CHAR),
  pc_tambahan_promo_produk_id    INTEGER,
  prod_code                      VARCHAR2(30),
  prod_name                      VARCHAR2(100),
  flag_budget                    VARCHAR2(5 CHAR),
  qty                            INTEGER,
  uom                            VARCHAR2(15 CHAR),
  harga_satuan                   NUMBER DEFAULT 0,
  nilai_total                    NUMBER DEFAULT 0,
  qty_converted                  NUMBER,
  uom_dcv                        VARCHAR2(15 CHAR),
  notes                          VARCHAR2(500),
  modified_dt                    DATE,
  modified_by                    VARCHAR2(50 CHAR)
);

COMMENT ON COLUMN tc_approval.no_po IS
    'No PO dari EBS';
COMMENT ON COLUMN tc_approval.line_po IS
    'Line no dari PO yang dipilih';
COMMENT ON COLUMN tc_approval.no_pr IS
    'No PR unt. PO tsb';
COMMENT ON COLUMN tc_approval.line_pr IS
    'No line PR';
COMMENT ON COLUMN tc_approval.pc_pengganti IS
    'No PC Pengganti + Line PC';
COMMENT ON COLUMN tc_approval.flag_budget IS
    'PB / TPB';
COMMENT ON COLUMN tc_approval.qty IS
    'Jumlah yang disetujui TC';
COMMENT ON COLUMN tc_approval.uom IS
    'uom jumlah yg disetujui, list dari EBS';
COMMENT ON COLUMN tc_approval.harga_satuan IS
    'excl ppn';
COMMENT ON COLUMN tc_approval.nilai_total IS
    'Nilai total sesuai uom dan nilai satuan';
COMMENT ON COLUMN tc_approval.qty_converted IS
    'Nilai hasil konversi uom dari uom ebs ke uom dcv';
COMMENT ON COLUMN tc_approval.uom_dcv IS
    'Uom dcv yg direquest distributor';
ALTER TABLE tc_approval ADD CONSTRAINT tc_approval_pk PRIMARY KEY ( id );

ALTER TABLE dcv_documents
    ADD CONSTRAINT dcv_doc_request_hdr_fk FOREIGN KEY ( dcvh_id )
        REFERENCES dcv_request ( dcvh_id );

ALTER TABLE dcv_user_role
    ADD CONSTRAINT dcv_role_user_role_fk FOREIGN KEY ( role_code )
        REFERENCES dcv_role ( role_code );

ALTER TABLE dcv_user_role
    ADD CONSTRAINT dcv_user_role_user_id_fk FOREIGN KEY ( user_id )
        REFERENCES dcv_user_access ( id );

ALTER TABLE disposisi
    ADD CONSTRAINT disposisi_dcv_fk FOREIGN KEY ( dcvh_id )
        REFERENCES dcv_request ( dcvh_id );

ALTER TABLE dokumen_realisasi
    ADD CONSTRAINT dok_realisasi_dcv_request_fk FOREIGN KEY ( dcvh_id )
        REFERENCES dcv_request ( dcvh_id );

ALTER TABLE request_dtl
    ADD CONSTRAINT request_dtl_hdr_fk FOREIGN KEY ( dcvh_id )
        REFERENCES dcv_request ( dcvh_id );

ALTER TABLE role_privs
    ADD CONSTRAINT role_privs_privs_fk FOREIGN KEY ( priv_id )
        REFERENCES dcv_privs ( id );

ALTER TABLE role_privs
    ADD CONSTRAINT role_privs_role_fk FOREIGN KEY ( role_code )
        REFERENCES dcv_role ( role_code );

ALTER TABLE tc_approval
    ADD CONSTRAINT req_line_breakdown_fk FOREIGN KEY ( dcvl_id )
        REFERENCES request_dtl ( dcvl_id );
