-- Generated by Oracle SQL Developer Data Modeler 18.1.0.082.1035
--   at:        2019-03-12 14:03:22 ICT
--   site:      Oracle Database 11g
--   type:      Oracle Database 11g



CREATE TABLE file_pendukung (
    id                   INTEGER NOT NULL,
    file_name            VARCHAR2(100 CHAR) NOT NULL,
    doc_type             VARCHAR2(15 CHAR),
    file_loc             VARCHAR2(500 CHAR),
    upload_time          DATE,
    request_hdr_req_id   INTEGER NOT NULL,
    keterangan           VARCHAR2(500)
);

ALTER TABLE file_pendukung ADD CONSTRAINT file_pendukung_pk PRIMARY KEY ( id );

CREATE TABLE holiday (
    id            INTEGER NOT NULL,
    start_dt      DATE,
    end_dt        DATE,
    description   VARCHAR2(50 CHAR)
);

ALTER TABLE holiday ADD CONSTRAINT holiday_pk PRIMARY KEY ( id );

CREATE TABLE message (
    id                   INTEGER NOT NULL,
    request_hdr_req_id   INTEGER NOT NULL,
    msg_type             VARCHAR2(10 CHAR),
    message              VARCHAR2(800 CHAR),
    create_time          DATE
);

ALTER TABLE message ADD CONSTRAINT message_pk PRIMARY KEY ( id );

CREATE TABLE req_line_breakdown (
    id               INTEGER NOT NULL,
    request_dtl_id   INTEGER NOT NULL,
    prod_code        VARCHAR2(30),
    prod_name        VARCHAR2(100),
    qty              INTEGER,
    uom              VARCHAR2(15 CHAR),
    nilai_satuan     NUMBER DEFAULT 0,
    value_total      NUMBER DEFAULT 0,
    mf_ot            VARCHAR2(2 CHAR),
    conversion_uom   NUMBER,
    notes            VARCHAR2(100)
);

ALTER TABLE req_line_breakdown ADD CONSTRAINT req_line_breakdown_pk PRIMARY KEY ( id );

CREATE TABLE request_dtl (
    id                    INTEGER NOT NULL,
    request_hdr_id        INTEGER NOT NULL,
    pc_lineno             VARCHAR2(50 CHAR),
    prod_class            VARCHAR2(40 CHAR),
    prod_class_desc       VARCHAR2(100 CHAR),
    prod_brand            VARCHAR2(40 CHAR),
    prod_brand_desc       VARCHAR2(100 CHAR),
    prod_ext              VARCHAR2(40 CHAR),
    prod_ext_desc         VARCHAR2(100 CHAR),
    prod_packaging        VARCHAR2(40 CHAR),
    prod_packaging_desc   VARCHAR2(100 CHAR),
    prod_variant          VARCHAR2(40 CHAR),
    prod_variant_desc     VARCHAR2(100 CHAR),
    prod_item             VARCHAR2(40 CHAR),
    prod_item_desc        VARCHAR2(100 CHAR),
    req_qty               INTEGER,
    req_uom               VARCHAR2(15 CHAR),
    req_value_exc         NUMBER DEFAULT 0,
    apr_value_exc         NUMBER DEFAULT 0,
    ppn                   NUMBER DEFAULT 0,
    taxcode               VARCHAR2(10 CHAR),
    pph_value             NUMBER DEFAULT 0,
    mf_val                NUMBER,
    ot_val                NUMBER,
    total_value_inc       NUMBER,
    selisih               NUMBER,
    notes                 VARCHAR2(100 CHAR)
);

ALTER TABLE request_dtl ADD CONSTRAINT request_dtl_pk PRIMARY KEY ( id );

CREATE TABLE request_hdr (
    req_id              INTEGER NOT NULL,
    customer            VARCHAR2(25 CHAR) NOT NULL,
    company             VARCHAR2(3 CHAR) NOT NULL,
    no_pc               VARCHAR2(100 CHAR) NOT NULL,
    key_pc              VARCHAR2(14 CHAR) NOT NULL,
    periode_dcv_start   DATE NOT NULL,
    periode_dcv_end     DATE,
    pc_kategori         VARCHAR2(5),
    pc_tipe             VARCHAR2(50),
    periode_pc_start    DATE,
    periode_pc_end      DATE,
    no_dcv              VARCHAR2(15 CHAR),
    prod_type           VARCHAR2(15),
    req_value           NUMBER DEFAULT 0,
    apr_value           NUMBER DEFAULT 0,
    req_time            DATE,
    file_complete       VARCHAR2(1 CHAR),
    reg_area_loc        VARCHAR2(60),
    pc_adds             VARCHAR2(100),
    last_status         VARCHAR2(30),
    no_faktur           VARCHAR2(30 CHAR)
);

ALTER TABLE request_hdr ADD CONSTRAINT request_hdr_pk PRIMARY KEY ( req_id );

ALTER TABLE file_pendukung
    ADD CONSTRAINT file_pendukung_request_hdr_fk FOREIGN KEY ( request_hdr_req_id )
        REFERENCES request_hdr ( req_id );

ALTER TABLE message
    ADD CONSTRAINT message_request_hdr_fk FOREIGN KEY ( request_hdr_req_id )
        REFERENCES request_hdr ( req_id );

ALTER TABLE req_line_breakdown
    ADD CONSTRAINT req_line_breakdown_fk FOREIGN KEY ( request_dtl_id )
        REFERENCES request_dtl ( id );

ALTER TABLE request_dtl
    ADD CONSTRAINT request_dtl_request_hdr_fk FOREIGN KEY ( request_hdr_id )
        REFERENCES request_hdr ( req_id );



-- Oracle SQL Developer Data Modeler Summary Report: 
-- 
-- CREATE TABLE                             6
-- CREATE INDEX                             0
-- ALTER TABLE                             10
-- CREATE VIEW                              0
-- ALTER VIEW                               0
-- CREATE PACKAGE                           0
-- CREATE PACKAGE BODY                      0
-- CREATE PROCEDURE                         0
-- CREATE FUNCTION                          0
-- CREATE TRIGGER                           0
-- ALTER TRIGGER                            0
-- CREATE COLLECTION TYPE                   0
-- CREATE STRUCTURED TYPE                   0
-- CREATE STRUCTURED TYPE BODY              0
-- CREATE CLUSTER                           0
-- CREATE CONTEXT                           0
-- CREATE DATABASE                          0
-- CREATE DIMENSION                         0
-- CREATE DIRECTORY                         0
-- CREATE DISK GROUP                        0
-- CREATE ROLE                              0
-- CREATE ROLLBACK SEGMENT                  0
-- CREATE SEQUENCE                          0
-- CREATE MATERIALIZED VIEW                 0
-- CREATE SYNONYM                           0
-- CREATE TABLESPACE                        0
-- CREATE USER                              0
-- 
-- DROP TABLESPACE                          0
-- DROP DATABASE                            0
-- 
-- REDACTION POLICY                         0
-- 
-- ORDS DROP SCHEMA                         0
-- ORDS ENABLE SCHEMA                       0
-- ORDS ENABLE OBJECT                       0
-- 
-- ERRORS                                   0
-- WARNINGS                                 0
