-- Generated by Oracle SQL Developer Data Modeler 18.1.0.082.1035
--   at:        2019-04-26 20:10:36 ICT
--   site:      Oracle Database 12c
--   type:      Oracle Database 12c

DROP TABLE wf_node CASCADE CONSTRAINTS;
CREATE TABLE wf_node (
  nodecode         VARCHAR2(10 CHAR) NOT NULL,
  node_desc        VARCHAR2(100 CHAR),
  nodetype         VARCHAR2(30 CHAR) NOT NULL,
  no_urut          INTEGER,
  bagian           VARCHAR2(25),
  execscript       VARCHAR2(100 CHAR),
  prime_route      VARCHAR2(1 CHAR),
  merge_count      INTEGER,
  sla1             NUMBER,
  sla2             NUMBER
);

ALTER TABLE wf_node ADD CONSTRAINT node_pk PRIMARY KEY ( nodecode );

DROP TABLE wf_rollback CASCADE CONSTRAINTS;
CREATE TABLE wf_rollback (
  id           INTEGER NOT NULL,
  no_request   VARCHAR2(30 CHAR),
  request_by   VARCHAR2(50 CHAR),
  dcvh_id      INTEGER,
  no_dcv       VARCHAR2(20 BYTE),
  beban_sla    VARCHAR2(25 CHAR),
  alasan       VARCHAR2(200 CHAR),
  status       VARCHAR2(15 CHAR),
  create_dt    DATE,
  create_by    VARCHAR2(25 CHAR)
);

COMMENT ON COLUMN wf_rollback.beban_sla IS
    'bagian yg menanggung sla';
COMMENT ON COLUMN wf_rollback.status IS
    'PENDING / MUNDUR / MAJU / CANCEL / COMPLETE';

ALTER TABLE wf_rollback ADD CONSTRAINT wf_rollback_pk PRIMARY KEY ( id );

DROP TABLE wf_rollback_approval CASCADE CONSTRAINTS;
CREATE TABLE wf_rollback_approval (
    id              INTEGER NOT NULL,
    rollback_id     INTEGER NOT NULL,
    bagian          VARCHAR2(25 CHAR),
    appvl_status    VARCHAR2(10 CHAR),
    approval_note   VARCHAR2(200 CHAR),
    approve_by      VARCHAR2(50 CHAR),
    approve_dt      DATE
);

COMMENT ON COLUMN wf_rollback_approval.bagian IS
    'bagian yg request-approve';
COMMENT ON COLUMN wf_rollback_approval.appvl_status IS
    'APPROVED/REJECT';

ALTER TABLE wf_rollback_approval ADD CONSTRAINT wf_rollback_approval_pk PRIMARY KEY ( id );

DROP TABLE wf_rollback_approver CASCADE CONSTRAINTS;
CREATE TABLE wf_rollback_approver (
    id              INTEGER NOT NULL,
    bagian          VARCHAR2(10 BYTE),
    approver_id     INTEGER,
    approver_name   VARCHAR2(30 BYTE)
);

ALTER TABLE wf_rollback_approver ADD CONSTRAINT wf_rollback_approver_pk PRIMARY KEY ( id );

DROP TABLE wf_rollback_flow CASCADE CONSTRAINTS;
CREATE TABLE wf_rollback_flow (
  id              INTEGER NOT NULL,
  rb_request_id   INTEGER NOT NULL,
  nourut          INTEGER,
  bagian          VARCHAR2(25 CHAR),
  node_code       VARCHAR2(10 CHAR),
  rb_in           VARCHAR2(3 CHAR),
  flag_approval   VARCHAR2(5 CHAR),
  modify_by       VARCHAR2(30 CHAR),
  modify_dt       DATE
);

COMMENT ON COLUMN wf_rollback_flow.rb_in IS
    'Y = include N = skip';

ALTER TABLE wf_rollback_flow ADD CONSTRAINT wf_rollback_flow_pk PRIMARY KEY ( id );

DROP TABLE wf_route CASCADE CONSTRAINTS;
CREATE TABLE wf_route (
    id              INTEGER NOT NULL,
    node_id         VARCHAR2(10 CHAR) NOT NULL,
    pilihan         INTEGER NOT NULL,
    description     VARCHAR2(60 CHAR),
    refnode         VARCHAR2(10 CHAR) NOT NULL,
    return_task     VARCHAR2(1 CHAR),
    document_task   VARCHAR2(1 CHAR),
    post_script     VARCHAR2(200 CHAR)
);

ALTER TABLE wf_route ADD CONSTRAINT wf_route_pk PRIMARY KEY ( id );

DROP TABLE wf_task CASCADE CONSTRAINTS;
CREATE TABLE wf_task (
  id                INTEGER NOT NULL,
  no_dcv            VARCHAR2(20 CHAR) NOT NULL,
  task_type         VARCHAR2(10 CHAR),
  assign_time       DATE,
  bagian            VARCHAR2(25 CHAR) NOT NULL,
  role_assigned     VARCHAR2(50 CHAR),
  progress_status   VARCHAR2(10 CHAR),
  nodecode          VARCHAR2(10 CHAR) NOT NULL,
  prev_task         INTEGER,
  tahapan           VARCHAR2(200 CHAR),
  decision          INTEGER,
  execscript        VARCHAR2(100 CHAR),
  next_task         INTEGER,
  next_node         VARCHAR2(10 CHAR),
  note              VARCHAR2(250 CHAR),
  prime_route       VARCHAR2(1 CHAR),
  return_task       VARCHAR2(1 CHAR),
  process_by        VARCHAR2(50 CHAR),
  process_time      DATE,
  sla               NUMBER,
  rollback_task     VARCHAR2(3 BYTE),
  rollback_id       INTEGER,
  beban_sla         VARCHAR2(25 CHAR),
  sorting_tag       VARCHAR2(1 CHAR),
  target_selesai    DATE
);
ALTER TABLE wf_task ADD CONSTRAINT wf_task_pk PRIMARY KEY ( id );

COMMENT ON COLUMN wf_task.task_type IS
    'humantask, merge, auto sched';
COMMENT ON COLUMN wf_task.progress_status IS
    'DONE, WORKING';
COMMENT ON COLUMN wf_task.return_task IS
    'apakah merupakan return task ?';
COMMENT ON COLUMN wf_task.sla IS
    'running sla tiap hari';
COMMENT ON COLUMN wf_task.beban_sla IS
  'yang menanggung beban sla untuk task ini, jika bukan bagian yg mengerjakan (kasus Rollback)';
COMMENT ON COLUMN wf_task.target_selesai IS
    'kapan harus selesai';

CREATE INDEX wf_task_dcvno_idx ON
    wf_task (
        no_dcv    ASC,
        nodecode    ASC,
        progress_status    ASC );
CREATE INDEX wf_task_type_idx ON
    wf_task (
        task_type    ASC,
        progress_status    ASC );

ALTER TABLE wf_rollback
    ADD CONSTRAINT wf_rollback_dcv_request_fk FOREIGN KEY ( dcvh_id )
        REFERENCES dcv_request ( dcvh_id );

ALTER TABLE wf_rollback_approval
    ADD CONSTRAINT wf_rollback_approval_fk FOREIGN KEY ( rollback_id )
        REFERENCES wf_rollback ( id );

ALTER TABLE wf_rollback_flow
    ADD CONSTRAINT wf_rollback_flow_fk FOREIGN KEY ( rb_request_id )
        REFERENCES wf_rollback ( id );

ALTER TABLE wf_route
    ADD CONSTRAINT wf_node_option_wf_node_fk FOREIGN KEY ( node_id )
        REFERENCES wf_node ( nodecode );

ALTER TABLE wf_route
    ADD CONSTRAINT wf_node_option_wf_node_fkv1 FOREIGN KEY ( refnode )
        REFERENCES wf_node ( nodecode );

ALTER TABLE wf_task
    ADD CONSTRAINT wf_task_wf_node_fk FOREIGN KEY ( nodecode )
        REFERENCES wf_node ( nodecode );

/*  SETUP DATA */

REM INSERTING into WF_NODE
SET DEFINE OFF;
Insert into WF_NODE (NODECODE,NODE_DESC,NODETYPE,NO_URUT,BAGIAN,EXECSCRIPT,PRIME_ROUTE,MERGE_COUNT,SLA1,SLA2) values ('AP2','Tunggu Selesai Buat Invoice - AP','Human',130,'AP',null,'Y',null,null,null);
Insert into WF_NODE (NODECODE,NODE_DESC,NODETYPE,NO_URUT,BAGIAN,EXECSCRIPT,PRIME_ROUTE,MERGE_COUNT,SLA1,SLA2) values ('TC2','Tunggu Terima PO & GR & Kwitansi & FP - TC','Human',100,'TC',null,'Y',null,null,null);
Insert into WF_NODE (NODECODE,NODE_DESC,NODETYPE,NO_URUT,BAGIAN,EXECSCRIPT,PRIME_ROUTE,MERGE_COUNT,SLA1,SLA2) values ('SCRP-1','TC or Sales','Script',26,'Distributor','wf_job.run_scrp1','Y',null,null,null);
Insert into WF_NODE (NODECODE,NODE_DESC,NODETYPE,NO_URUT,BAGIAN,EXECSCRIPT,PRIME_ROUTE,MERGE_COUNT,SLA1,SLA2) values ('D0','Entri Data DCV','Start',10,'Distributor',null,'Y',null,null,null);
Insert into WF_NODE (NODECODE,NODE_DESC,NODETYPE,NO_URUT,BAGIAN,EXECSCRIPT,PRIME_ROUTE,MERGE_COUNT,SLA1,SLA2) values ('SL1','Sedang Proses Sales','Human',20,'Sales',null,'Y',null,null,null);
Insert into WF_NODE (NODECODE,NODE_DESC,NODETYPE,NO_URUT,BAGIAN,EXECSCRIPT,PRIME_ROUTE,MERGE_COUNT,SLA1,SLA2) values ('END','LUNAS','End',170,'AP',null,'Y',null,null,null);
Insert into WF_NODE (NODECODE,NODE_DESC,NODETYPE,NO_URUT,BAGIAN,EXECSCRIPT,PRIME_ROUTE,MERGE_COUNT,SLA1,SLA2) values ('TC1','Sedang Proses TC','Human',30,'TC',null,'Y',null,null,null);
Insert into WF_NODE (NODECODE,NODE_DESC,NODETYPE,NO_URUT,BAGIAN,EXECSCRIPT,PRIME_ROUTE,MERGE_COUNT,SLA1,SLA2) values ('SCRP-2','Back Process','Script',34,'TC','wf_job.run_scrp2','Y',null,null,null);
Insert into WF_NODE (NODECODE,NODE_DESC,NODETYPE,NO_URUT,BAGIAN,EXECSCRIPT,PRIME_ROUTE,MERGE_COUNT,SLA1,SLA2) values ('PR1','Generate PO - Promo','Human',32,'Promo',null,'Y',null,null,null);
Insert into WF_NODE (NODECODE,NODE_DESC,NODETYPE,NO_URUT,BAGIAN,EXECSCRIPT,PRIME_ROUTE,MERGE_COUNT,SLA1,SLA2) values ('D1','Sedang Proses Distributor','Human',25,'Distributor',null,'Y',null,null,null);
Insert into WF_NODE (NODECODE,NODE_DESC,NODETYPE,NO_URUT,BAGIAN,EXECSCRIPT,PRIME_ROUTE,MERGE_COUNT,SLA1,SLA2) values ('D3','Upload no Resi Kwitansi','Human',105,'Distributor',null,'N',null,null,null);
Insert into WF_NODE (NODECODE,NODE_DESC,NODETYPE,NO_URUT,BAGIAN,EXECSCRIPT,PRIME_ROUTE,MERGE_COUNT,SLA1,SLA2) values ('TC3','Terima Kwitansi Asli','Human',106,'TC',null,'N',null,null,null);
Insert into WF_NODE (NODECODE,NODE_DESC,NODETYPE,NO_URUT,BAGIAN,EXECSCRIPT,PRIME_ROUTE,MERGE_COUNT,SLA1,SLA2) values ('TC4','Tunggu Serah Kwitansi FP PO GR - TC','Human',110,'TC',null,'Y',null,null,null);
Insert into WF_NODE (NODECODE,NODE_DESC,NODETYPE,NO_URUT,BAGIAN,EXECSCRIPT,PRIME_ROUTE,MERGE_COUNT,SLA1,SLA2) values ('PR4','Tunggu Serah Kwitansi, FP, PO, GR - Promo','Human',90,'Promo',null,'Y',null,null,null);
Insert into WF_NODE (NODECODE,NODE_DESC,NODETYPE,NO_URUT,BAGIAN,EXECSCRIPT,PRIME_ROUTE,MERGE_COUNT,SLA1,SLA2) values ('AP1','Tunggu Terima PO & GR & Kwitansi & Kwitansi Asli & FP - AP','Human',120,'AP',null,'Y',null,null,null);
Insert into WF_NODE (NODECODE,NODE_DESC,NODETYPE,NO_URUT,BAGIAN,EXECSCRIPT,PRIME_ROUTE,MERGE_COUNT,SLA1,SLA2) values ('TX2','Tunggu Serah Kwitansi dan FP - Tax','Human',60,'Tax',null,'Y',null,null,null);
Insert into WF_NODE (NODECODE,NODE_DESC,NODETYPE,NO_URUT,BAGIAN,EXECSCRIPT,PRIME_ROUTE,MERGE_COUNT,SLA1,SLA2) values ('D2','Tunggu Attach Kwitansi & FP - Distributor','Human',40,'Distributor',null,'Y',null,null,null);
Insert into WF_NODE (NODECODE,NODE_DESC,NODETYPE,NO_URUT,BAGIAN,EXECSCRIPT,PRIME_ROUTE,MERGE_COUNT,SLA1,SLA2) values ('TX1','Tunggu Verify Kwitansi & FP - Tax','Human',50,'Tax',null,'Y',null,null,null);
Insert into WF_NODE (NODECODE,NODE_DESC,NODETYPE,NO_URUT,BAGIAN,EXECSCRIPT,PRIME_ROUTE,MERGE_COUNT,SLA1,SLA2) values ('SCRP-3','Disposisi Normal atau Hold','Script',132,'AP','wf_job.run_scrp3','Y',null,null,null);
Insert into WF_NODE (NODECODE,NODE_DESC,NODETYPE,NO_URUT,BAGIAN,EXECSCRIPT,PRIME_ROUTE,MERGE_COUNT,SLA1,SLA2) values ('STOP','STOP','End',200,'TC',null,'N',null,null,null);
Insert into WF_NODE (NODECODE,NODE_DESC,NODETYPE,NO_URUT,BAGIAN,EXECSCRIPT,PRIME_ROUTE,MERGE_COUNT,SLA1,SLA2) values ('PR2','Tunggu Terima Kwitansi dan FP - Promo','Human',70,'Promo',null,'Y',null,null,null);
Insert into WF_NODE (NODECODE,NODE_DESC,NODETYPE,NO_URUT,BAGIAN,EXECSCRIPT,PRIME_ROUTE,MERGE_COUNT,SLA1,SLA2) values ('PR3','Buat GR - Promo','Human',80,'Promo',null,'Y',null,null,null);
Insert into WF_NODE (NODECODE,NODE_DESC,NODETYPE,NO_URUT,BAGIAN,EXECSCRIPT,PRIME_ROUTE,MERGE_COUNT,SLA1,SLA2) values ('AP3','Tunggu Open Disposisi Hold - AP','Human',140,'AP',null,'Y',null,null,null);
Insert into WF_NODE (NODECODE,NODE_DESC,NODETYPE,NO_URUT,BAGIAN,EXECSCRIPT,PRIME_ROUTE,MERGE_COUNT,SLA1,SLA2) values ('AP4','Tunggu Payment - AP','Human',150,'AP',null,'Y',null,null,null);
Insert into WF_NODE (NODECODE,NODE_DESC,NODETYPE,NO_URUT,BAGIAN,EXECSCRIPT,PRIME_ROUTE,MERGE_COUNT,SLA1,SLA2) values ('AR1','Tunggu ARAP Netting - AR','Human',160,'AR',null,'Y',null,null,null);
Insert into WF_NODE (NODECODE,NODE_DESC,NODETYPE,NO_URUT,BAGIAN,EXECSCRIPT,PRIME_ROUTE,MERGE_COUNT,SLA1,SLA2) values ('SPLT1','Tunggu Serah Kwitansi dan FP - Tax','Split',1000,'Tax',null,'Y',null,null,null);
Insert into WF_NODE (NODECODE,NODE_DESC,NODETYPE,NO_URUT,BAGIAN,EXECSCRIPT,PRIME_ROUTE,MERGE_COUNT,SLA1,SLA2) values ('SCRP-4','Terminate DCV','Script',140,'Distributor','wf_job.run_scrp4','Y',null,null,null);
COMMIT;


REM INSERTING into WF_ROUTE
SET DEFINE OFF;
Insert into WF_ROUTE (ID,NODE_ID,PILIHAN,DESCRIPTION,REFNODE,RETURN_TASK,DOCUMENT_TASK,POST_SCRIPT) values (60,'AP1',1,'Terima PO & GR & Kwitansi & Kwitansi Asli & FP','AP2',null,'Y',null);
Insert into WF_ROUTE (ID,NODE_ID,PILIHAN,DESCRIPTION,REFNODE,RETURN_TASK,DOCUMENT_TASK,POST_SCRIPT) values (61,'AP1',2,'Tolak Terima PO & GR & Kwitansi & Kwitansi Asli & FP','TC4','Y','Y',null);
Insert into WF_ROUTE (ID,NODE_ID,PILIHAN,DESCRIPTION,REFNODE,RETURN_TASK,DOCUMENT_TASK,POST_SCRIPT) values (70,'AR1',1,'Alihkan ke Payment','AP4',null,null,null);
Insert into WF_ROUTE (ID,NODE_ID,PILIHAN,DESCRIPTION,REFNODE,RETURN_TASK,DOCUMENT_TASK,POST_SCRIPT) values (17,'D2',1,'Attach Kwitansi & FP','TX1',null,null,null);
Insert into WF_ROUTE (ID,NODE_ID,PILIHAN,DESCRIPTION,REFNODE,RETURN_TASK,DOCUMENT_TASK,POST_SCRIPT) values (18,'D3',1,'Serah Kwitansi Asli','TC3',null,null,null);
Insert into WF_ROUTE (ID,NODE_ID,PILIHAN,DESCRIPTION,REFNODE,RETURN_TASK,DOCUMENT_TASK,POST_SCRIPT) values (12,'D1',2,'Terminate DCV','SCRP-4',null,null,null);
Insert into WF_ROUTE (ID,NODE_ID,PILIHAN,DESCRIPTION,REFNODE,RETURN_TASK,DOCUMENT_TASK,POST_SCRIPT) values (20,'SL1',1,'Disetujui','TC1',null,null,null);
Insert into WF_ROUTE (ID,NODE_ID,PILIHAN,DESCRIPTION,REFNODE,RETURN_TASK,DOCUMENT_TASK,POST_SCRIPT) values (21,'SL1',2,'Ditolak','D1','Y',null,null);
Insert into WF_ROUTE (ID,NODE_ID,PILIHAN,DESCRIPTION,REFNODE,RETURN_TASK,DOCUMENT_TASK,POST_SCRIPT) values (30,'TC1',1,'Disetujui ','D2',null,null,null);
Insert into WF_ROUTE (ID,NODE_ID,PILIHAN,DESCRIPTION,REFNODE,RETURN_TASK,DOCUMENT_TASK,POST_SCRIPT) values (31,'TC1',2,'Ditolak','D1','Y',null,null);
Insert into WF_ROUTE (ID,NODE_ID,PILIHAN,DESCRIPTION,REFNODE,RETURN_TASK,DOCUMENT_TASK,POST_SCRIPT) values (34,'TC2',1,'Terima PO,GR,Kwitansi,FP','TC4',null,'Y',null);
Insert into WF_ROUTE (ID,NODE_ID,PILIHAN,DESCRIPTION,REFNODE,RETURN_TASK,DOCUMENT_TASK,POST_SCRIPT) values (35,'TC2',2,'Tolak PO,GR,Kwitansi,FP','PR4','Y','Y',null);
Insert into WF_ROUTE (ID,NODE_ID,PILIHAN,DESCRIPTION,REFNODE,RETURN_TASK,DOCUMENT_TASK,POST_SCRIPT) values (37,'TC3',1,'Terima kwitansi asli','STOP',null,'Y',null);
Insert into WF_ROUTE (ID,NODE_ID,PILIHAN,DESCRIPTION,REFNODE,RETURN_TASK,DOCUMENT_TASK,POST_SCRIPT) values (39,'TC4',1,'Serah PO, GR, Kwitansi, Kwitansi Asli & FP ','AP1',null,'Y',null);
Insert into WF_ROUTE (ID,NODE_ID,PILIHAN,DESCRIPTION,REFNODE,RETURN_TASK,DOCUMENT_TASK,POST_SCRIPT) values (38,'TC3',2,'Tolak kwitansi asli','D3','Y','Y',null);
Insert into WF_ROUTE (ID,NODE_ID,PILIHAN,DESCRIPTION,REFNODE,RETURN_TASK,DOCUMENT_TASK,POST_SCRIPT) values (40,'TX1',1,'Verify Kwitansi & FP Valid','SPLT1',null,null,null);
Insert into WF_ROUTE (ID,NODE_ID,PILIHAN,DESCRIPTION,REFNODE,RETURN_TASK,DOCUMENT_TASK,POST_SCRIPT) values (41,'TX1',2,'Verify Kwitansi & FP Tidak valid','D2','Y',null,null);
Insert into WF_ROUTE (ID,NODE_ID,PILIHAN,DESCRIPTION,REFNODE,RETURN_TASK,DOCUMENT_TASK,POST_SCRIPT) values (42,'TX2',1,'Serah Kwitansi & FP','PR2',null,'Y',null);
Insert into WF_ROUTE (ID,NODE_ID,PILIHAN,DESCRIPTION,REFNODE,RETURN_TASK,DOCUMENT_TASK,POST_SCRIPT) values (50,'PR1',1,'Selesai Buat PO','TC1',null,null,null);
Insert into WF_ROUTE (ID,NODE_ID,PILIHAN,DESCRIPTION,REFNODE,RETURN_TASK,DOCUMENT_TASK,POST_SCRIPT) values (51,'PR2',1,'Terima Kwitansi & FP','PR3',null,'Y',null);
Insert into WF_ROUTE (ID,NODE_ID,PILIHAN,DESCRIPTION,REFNODE,RETURN_TASK,DOCUMENT_TASK,POST_SCRIPT) values (52,'PR2',2,'Tolak Terima Kwitansi & FP','TX2','Y','Y',null);
Insert into WF_ROUTE (ID,NODE_ID,PILIHAN,DESCRIPTION,REFNODE,RETURN_TASK,DOCUMENT_TASK,POST_SCRIPT) values (220,'SCRP-3',1,'Disp.Normal or Bayar ke Payment','AP4',null,null,null);
Insert into WF_ROUTE (ID,NODE_ID,PILIHAN,DESCRIPTION,REFNODE,RETURN_TASK,DOCUMENT_TASK,POST_SCRIPT) values (221,'SCRP-3',2,'Disposisi Hold ke Open Disp.Hold','AP3',null,null,null);
Insert into WF_ROUTE (ID,NODE_ID,PILIHAN,DESCRIPTION,REFNODE,RETURN_TASK,DOCUMENT_TASK,POST_SCRIPT) values (53,'PR3',1,'Selesai Buat GR','PR4',null,null,null);
Insert into WF_ROUTE (ID,NODE_ID,PILIHAN,DESCRIPTION,REFNODE,RETURN_TASK,DOCUMENT_TASK,POST_SCRIPT) values (210,'SCRP-2',1,'Back Proses','TC1',null,null,null);
Insert into WF_ROUTE (ID,NODE_ID,PILIHAN,DESCRIPTION,REFNODE,RETURN_TASK,DOCUMENT_TASK,POST_SCRIPT) values (10,'D1',1,'Submit DCV','SCRP-1',null,null,null);
Insert into WF_ROUTE (ID,NODE_ID,PILIHAN,DESCRIPTION,REFNODE,RETURN_TASK,DOCUMENT_TASK,POST_SCRIPT) values (32,'TC1',3,'Back Process','SCRP-2','Y',null,null);
Insert into WF_ROUTE (ID,NODE_ID,PILIHAN,DESCRIPTION,REFNODE,RETURN_TASK,DOCUMENT_TASK,POST_SCRIPT) values (200,'SCRP-1',1,'Submit ulang DCV','SL1',null,null,null);
Insert into WF_ROUTE (ID,NODE_ID,PILIHAN,DESCRIPTION,REFNODE,RETURN_TASK,DOCUMENT_TASK,POST_SCRIPT) values (201,'SCRP-1',2,'Submit ulang DCV','TC1',null,null,null);
Insert into WF_ROUTE (ID,NODE_ID,PILIHAN,DESCRIPTION,REFNODE,RETURN_TASK,DOCUMENT_TASK,POST_SCRIPT) values (33,'TC1',4,'Buat PO','PR1',null,null,null);
Insert into WF_ROUTE (ID,NODE_ID,PILIHAN,DESCRIPTION,REFNODE,RETURN_TASK,DOCUMENT_TASK,POST_SCRIPT) values (54,'PR4',1,'Serah PO & GR & Kwitansi & FP','TC2',null,'Y',null);
Insert into WF_ROUTE (ID,NODE_ID,PILIHAN,DESCRIPTION,REFNODE,RETURN_TASK,DOCUMENT_TASK,POST_SCRIPT) values (62,'AP2',1,'Selesai Buat Invoice','SCRP-3',null,null,null);
Insert into WF_ROUTE (ID,NODE_ID,PILIHAN,DESCRIPTION,REFNODE,RETURN_TASK,DOCUMENT_TASK,POST_SCRIPT) values (63,'AP3',1,'Open Disposisi Hold','AP4',null,null,null);
Insert into WF_ROUTE (ID,NODE_ID,PILIHAN,DESCRIPTION,REFNODE,RETURN_TASK,DOCUMENT_TASK,POST_SCRIPT) values (64,'AP4',1,'Alihkan ke ARAP Netting','AR1',null,null,null);
Insert into WF_ROUTE (ID,NODE_ID,PILIHAN,DESCRIPTION,REFNODE,RETURN_TASK,DOCUMENT_TASK,POST_SCRIPT) values (230,'SPLT1',1,'Ke Distributor','D3',null,null,null);
Insert into WF_ROUTE (ID,NODE_ID,PILIHAN,DESCRIPTION,REFNODE,RETURN_TASK,DOCUMENT_TASK,POST_SCRIPT) values (231,'SPLT1',2,'KE PROMO','TX2',null,null,null);
COMMIT;
