REM INSERTING into DCV.SEC_ROLE
SET DEFINE OFF;
Insert into DCV.SEC_ROLE (ID,ROLE_CODE,ROLE_DESC,SLA1,SLA2,ROLE_LEVEL,ROLE_PARENT) values (1,'DISTI','DISTRIBUTOR',null,null,null,null);
Insert into DCV.SEC_ROLE (ID,ROLE_CODE,ROLE_DESC,SLA1,SLA2,ROLE_LEVEL,ROLE_PARENT) values (2,'SALES','SALES',null,null,null,null);
Insert into DCV.SEC_ROLE (ID,ROLE_CODE,ROLE_DESC,SLA1,SLA2,ROLE_LEVEL,ROLE_PARENT) values (3,'TC','TC',null,null,null,null);
Insert into DCV.SEC_ROLE (ID,ROLE_CODE,ROLE_DESC,SLA1,SLA2,ROLE_LEVEL,ROLE_PARENT) values (4,'TAX','TAX',null,null,null,null);
Insert into DCV.SEC_ROLE (ID,ROLE_CODE,ROLE_DESC,SLA1,SLA2,ROLE_LEVEL,ROLE_PARENT) values (5,'PROMO','PROMO',null,null,null,null);

REM INSERTING into DCV.WF_NODE
SET DEFINE OFF;
Insert into DCV.WF_NODE (NODECODE,NODE_DESC,NODETYPE,DEPARTMENT,EXECSCRIPT,KETR_INSTRUKSI,PRIME_ROUTE) values ('TC2','Collect Dokumen Fisik','Human',3,null,'Terima dokumen fisik dari Tax dan Distributor','Y');
Insert into DCV.WF_NODE (NODECODE,NODE_DESC,NODETYPE,DEPARTMENT,EXECSCRIPT,KETR_INSTRUKSI,PRIME_ROUTE) values ('TX4','Update PPh','Human',4,null,'Update PPH sesuai dgn dokumen PO lalu kirim ke TC','Y');
Insert into DCV.WF_NODE (NODECODE,NODE_DESC,NODETYPE,DEPARTMENT,EXECSCRIPT,KETR_INSTRUKSI,PRIME_ROUTE) values ('D0','Entri Data DCV','Start',1,null,null,'Y');
Insert into DCV.WF_NODE (NODECODE,NODE_DESC,NODETYPE,DEPARTMENT,EXECSCRIPT,KETR_INSTRUKSI,PRIME_ROUTE) values ('SL1','Proses Sales','Human',2,null,'Silakan approve/reject DCV ini','Y');
Insert into DCV.WF_NODE (NODECODE,NODE_DESC,NODETYPE,DEPARTMENT,EXECSCRIPT,KETR_INSTRUKSI,PRIME_ROUTE) values ('END','End','End',null,null,null,'Y');
Insert into DCV.WF_NODE (NODECODE,NODE_DESC,NODETYPE,DEPARTMENT,EXECSCRIPT,KETR_INSTRUKSI,PRIME_ROUTE) values ('TC1','Proses TC','Human',3,null,'TC diharapkan input keterangan kwitansi, PPN serta breakdown PC-line','Y');
Insert into DCV.WF_NODE (NODECODE,NODE_DESC,NODETYPE,DEPARTMENT,EXECSCRIPT,KETR_INSTRUKSI,PRIME_ROUTE) values ('TX1','Cek Ketr. Kwitansi','Human',4,null,'Cek keterangan kwitansi dan flag PPN','Y');
Insert into DCV.WF_NODE (NODECODE,NODE_DESC,NODETYPE,DEPARTMENT,EXECSCRIPT,KETR_INSTRUKSI,PRIME_ROUTE) values ('D1','Upload Kwitansi + Faktur Pajak','Human',1,null,'Harap upload dokumen kwitansi dan faktur pajak, serta entri no faktur','Y');
Insert into DCV.WF_NODE (NODECODE,NODE_DESC,NODETYPE,DEPARTMENT,EXECSCRIPT,KETR_INSTRUKSI,PRIME_ROUTE) values ('TX2','Verify Kwitansi + FP','Human',4,null,'Cetak faktur dan kwitansi, dan revisi no faktur jika salah','Y');
Insert into DCV.WF_NODE (NODECODE,NODE_DESC,NODETYPE,DEPARTMENT,EXECSCRIPT,KETR_INSTRUKSI,PRIME_ROUTE) values ('PR1','Create PO GR','Human',5,null,null,'Y');
Insert into DCV.WF_NODE (NODECODE,NODE_DESC,NODETYPE,DEPARTMENT,EXECSCRIPT,KETR_INSTRUKSI,PRIME_ROUTE) values ('D3','Proses Reject','Human',1,null,'DCV ini ditolak. Silakan Terminate','Y');
Insert into DCV.WF_NODE (NODECODE,NODE_DESC,NODETYPE,DEPARTMENT,EXECSCRIPT,KETR_INSTRUKSI,PRIME_ROUTE) values ('D2','Update no Resi','Human',1,null,'Silakan upload / update No Resi Faktur','N');
Insert into DCV.WF_NODE (NODECODE,NODE_DESC,NODETYPE,DEPARTMENT,EXECSCRIPT,KETR_INSTRUKSI,PRIME_ROUTE) values ('TC3','Collect Dokumen Fisik','Human',3,null,'Terima dokumen fisik dari Tax dan Distributor','Y');
Insert into DCV.WF_NODE (NODECODE,NODE_DESC,NODETYPE,DEPARTMENT,EXECSCRIPT,KETR_INSTRUKSI,PRIME_ROUTE) values ('TC5','Serah Dokumen Fisik','Human',3,null,'Serahkan dokumen Kwitansi, Faktur Pajak, PO, GR ke bagian AP','Y');
Insert into DCV.WF_NODE (NODECODE,NODE_DESC,NODETYPE,DEPARTMENT,EXECSCRIPT,KETR_INSTRUKSI,PRIME_ROUTE) values ('TX3','Terima Kw-c, FP, PO, GR','Human',4,null,'Terima atau tolak dokumen dari Promo','Y');
Insert into DCV.WF_NODE (NODECODE,NODE_DESC,NODETYPE,DEPARTMENT,EXECSCRIPT,KETR_INSTRUKSI,PRIME_ROUTE) values ('AP1','Proses Finance','Auto',null,null,null,'Y');
Insert into DCV.WF_NODE (NODECODE,NODE_DESC,NODETYPE,DEPARTMENT,EXECSCRIPT,KETR_INSTRUKSI,PRIME_ROUTE) values ('TC4','Merge Collect dokumen Fisik','Merge',null,null,null,'Y');

REM INSERTING into DCV.WF_NODE_OPTION
SET DEFINE OFF;
Insert into DCV.WF_NODE_OPTION (ID,NODE_ID,PILIHAN,DESCRIPTION,REFNODE,PANGKAT,SP_ASSIGNMENT,RETURN_TASK) values (1,'D1',1,'Upload Kwitansi + Faktur Pajak','TX2',null,null,null);
Insert into DCV.WF_NODE_OPTION (ID,NODE_ID,PILIHAN,DESCRIPTION,REFNODE,PANGKAT,SP_ASSIGNMENT,RETURN_TASK) values (2,'D1',1,'Upload Kwitansi + Faktur Pajak','D2',null,null,null);
Insert into DCV.WF_NODE_OPTION (ID,NODE_ID,PILIHAN,DESCRIPTION,REFNODE,PANGKAT,SP_ASSIGNMENT,RETURN_TASK) values (3,'D2',1,'Update Resi Kwitansi','TC2',null,null,null);
Insert into DCV.WF_NODE_OPTION (ID,NODE_ID,PILIHAN,DESCRIPTION,REFNODE,PANGKAT,SP_ASSIGNMENT,RETURN_TASK) values (4,'D3',1,'Terminate','TERM',null,null,null);
Insert into DCV.WF_NODE_OPTION (ID,NODE_ID,PILIHAN,DESCRIPTION,REFNODE,PANGKAT,SP_ASSIGNMENT,RETURN_TASK) values (5,'SL1',1,'Approve','TC1',null,null,null);
Insert into DCV.WF_NODE_OPTION (ID,NODE_ID,PILIHAN,DESCRIPTION,REFNODE,PANGKAT,SP_ASSIGNMENT,RETURN_TASK) values (6,'SL1',2,'Reject','D3',null,null,'Y');
Insert into DCV.WF_NODE_OPTION (ID,NODE_ID,PILIHAN,DESCRIPTION,REFNODE,PANGKAT,SP_ASSIGNMENT,RETURN_TASK) values (7,'TC1',1,'Approve','TX1',null,null,null);
Insert into DCV.WF_NODE_OPTION (ID,NODE_ID,PILIHAN,DESCRIPTION,REFNODE,PANGKAT,SP_ASSIGNMENT,RETURN_TASK) values (8,'TC1',2,'Reject','D3',null,null,'Y');
Insert into DCV.WF_NODE_OPTION (ID,NODE_ID,PILIHAN,DESCRIPTION,REFNODE,PANGKAT,SP_ASSIGNMENT,RETURN_TASK) values (9,'TC2',1,'Terima Kwitansi asli','TC4',null,null,null);
Insert into DCV.WF_NODE_OPTION (ID,NODE_ID,PILIHAN,DESCRIPTION,REFNODE,PANGKAT,SP_ASSIGNMENT,RETURN_TASK) values (10,'TC2',2,'Tolak Kwitansi asli','D2',null,null,'Y');
Insert into DCV.WF_NODE_OPTION (ID,NODE_ID,PILIHAN,DESCRIPTION,REFNODE,PANGKAT,SP_ASSIGNMENT,RETURN_TASK) values (11,'TC3',1,'Terima Kw-c, FP, PO, GR','TC4',null,null,null);
Insert into DCV.WF_NODE_OPTION (ID,NODE_ID,PILIHAN,DESCRIPTION,REFNODE,PANGKAT,SP_ASSIGNMENT,RETURN_TASK) values (13,'TC5',1,'Serah Kw-a, Kw-c, FP, PO, GR','AP1',null,null,null);
Insert into DCV.WF_NODE_OPTION (ID,NODE_ID,PILIHAN,DESCRIPTION,REFNODE,PANGKAT,SP_ASSIGNMENT,RETURN_TASK) values (12,'TC3',2,'Tolak Kw-c, FP, PO, GR','TX3',null,null,'Y');
Insert into DCV.WF_NODE_OPTION (ID,NODE_ID,PILIHAN,DESCRIPTION,REFNODE,PANGKAT,SP_ASSIGNMENT,RETURN_TASK) values (14,'TX1',1,'Approve','D1',null,null,null);
Insert into DCV.WF_NODE_OPTION (ID,NODE_ID,PILIHAN,DESCRIPTION,REFNODE,PANGKAT,SP_ASSIGNMENT,RETURN_TASK) values (15,'TX1',2,'Reject','TC1',null,null,'Y');
Insert into DCV.WF_NODE_OPTION (ID,NODE_ID,PILIHAN,DESCRIPTION,REFNODE,PANGKAT,SP_ASSIGNMENT,RETURN_TASK) values (16,'TX2',1,'Serah Kw-c, FP','PR1',null,null,null);
Insert into DCV.WF_NODE_OPTION (ID,NODE_ID,PILIHAN,DESCRIPTION,REFNODE,PANGKAT,SP_ASSIGNMENT,RETURN_TASK) values (17,'TX2',2,'Reject','D1',null,null,'Y');
Insert into DCV.WF_NODE_OPTION (ID,NODE_ID,PILIHAN,DESCRIPTION,REFNODE,PANGKAT,SP_ASSIGNMENT,RETURN_TASK) values (18,'TX3',1,'Terima Kw-c, FP, PO, GR','TX4',null,null,null);
Insert into DCV.WF_NODE_OPTION (ID,NODE_ID,PILIHAN,DESCRIPTION,REFNODE,PANGKAT,SP_ASSIGNMENT,RETURN_TASK) values (19,'TX3',2,'Tolak Kw-c, FP, PO, GR','PR3',null,null,'Y');
Insert into DCV.WF_NODE_OPTION (ID,NODE_ID,PILIHAN,DESCRIPTION,REFNODE,PANGKAT,SP_ASSIGNMENT,RETURN_TASK) values (20,'TX4',1,'Kirim Kw-c, FP, PO, GR','TC2',null,null,null);
Insert into DCV.WF_NODE_OPTION (ID,NODE_ID,PILIHAN,DESCRIPTION,REFNODE,PANGKAT,SP_ASSIGNMENT,RETURN_TASK) values (21,'PR1',1,'Terima Kw-c, FP','PR2',null,null,null);
Insert into DCV.WF_NODE_OPTION (ID,NODE_ID,PILIHAN,DESCRIPTION,REFNODE,PANGKAT,SP_ASSIGNMENT,RETURN_TASK) values (22,'PR1',2,'Tolak Kw-c, FP','TX2',null,null,'Y');
Insert into DCV.WF_NODE_OPTION (ID,NODE_ID,PILIHAN,DESCRIPTION,REFNODE,PANGKAT,SP_ASSIGNMENT,RETURN_TASK) values (23,'PR2',1,'Create PR - GR','PR3',null,null,null);
Insert into DCV.WF_NODE_OPTION (ID,NODE_ID,PILIHAN,DESCRIPTION,REFNODE,PANGKAT,SP_ASSIGNMENT,RETURN_TASK) values (24,'PR3',1,'Serah Kw-c, FP, PO, GR','TX3',null,null,null);

REM INSERTING into DCV.HOLIDAY
SET DEFINE OFF;
Insert into DCV.HOLIDAY (ID,START_DT,END_DT,DESCRIPTION) values (1,to_date('07-MAR-19','DD-MON-RR'),to_date('07-MAR-19','DD-MON-RR'),'Hari Raya Nyepi');
Insert into DCV.HOLIDAY (ID,START_DT,END_DT,DESCRIPTION) values (2,to_date('03-APR-19','DD-MON-RR'),to_date('03-APR-19','DD-MON-RR'),'Hari Raya Nyepi');
Insert into DCV.HOLIDAY (ID,START_DT,END_DT,DESCRIPTION) values (3,to_date('19-APR-19','DD-MON-RR'),to_date('19-APR-19','DD-MON-RR'),'Isra Mi''raj');

BEGIN
FOR I IN 201903..203012 LOOP
  INSERT INTO DCV_NUMBER (PERIOD, LASTNUM, MODIFIED_DT)
  VALUES (I, 0, SYSDATE);
END LOOP;
END;
